import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs/promises'

const schemaSource = await fs.readFile(new URL('../src/services/flowAiSchema.js', import.meta.url), 'utf8')
const workspaceSource = await fs.readFile(new URL('../src/components/FlowAIWorkspace.jsx', import.meta.url), 'utf8')
const runtimeSource = await fs.readFile(new URL('../src/services/flowAiRuntime.js', import.meta.url), 'utf8')
const comfyuiSource = await fs.readFile(new URL('../src/services/comfyui.js', import.meta.url), 'utf8')
const workflowSetupSource = await fs.readFile(new URL('../src/components/WorkflowSetupSection.jsx', import.meta.url), 'utf8')
const settingsSource = await fs.readFile(new URL('../src/components/SettingsModal.jsx', import.meta.url), 'utf8')
const appSource = await fs.readFile(new URL('../src/App.jsx', import.meta.url), 'utf8')
const generateWorkspaceSource = await fs.readFile(new URL('../src/components/GenerateWorkspace.jsx', import.meta.url), 'utf8')
const irodoriVoiceCloneSource = await fs.readFile(new URL('../src/components/generate/IrodoriVoiceCloneCreator.jsx', import.meta.url), 'utf8')
const generateCatalogSource = await fs.readFile(new URL('../src/config/generateWorkflowCatalog.js', import.meta.url), 'utf8')
const assetsPanelSource = await fs.readFile(new URL('../src/components/panels/AssetsPanel.jsx', import.meta.url), 'utf8')
const communityModelBrowserSource = await fs.readFile(new URL('../src/components/generate/CommunityModelBrowser.jsx', import.meta.url), 'utf8')
const fileSystemSource = await fs.readFile(new URL('../src/services/fileSystem.js', import.meta.url), 'utf8')
const electronMainSource = await fs.readFile(new URL('../electron/main.js', import.meta.url), 'utf8')
const electronPreloadSource = await fs.readFile(new URL('../electron/preload.js', import.meta.url), 'utf8')

test('new CANVAS projects start empty and keep the Z-Image + LTX T2V preset in the template menu', () => {
  assert.match(schemaSource, /id: 'text-to-video',[\s\S]*?label: 'Z-Image \+ LTX T2V'/)
  assert.match(schemaSource, /createDefaultFlowAiProjectData\(\)[\s\S]*?name: 'Blank Canvas',[\s\S]*?templateId: 'blank'/)
  assert.match(schemaSource, /: \[createFlowDocument\(\{ name: 'Blank Canvas', templateId: 'blank' \}\)\]/)
})

test('Backstage cards open LoRA Factory recipes without remounting CANVAS', () => {
  assert.doesNotMatch(generateWorkspaceSource, /generate\.mode\.skills/)
  assert.match(generateWorkspaceSource, /manifest\.presentation === 'recipe'/)
  assert.match(generateWorkspaceSource, /onOpenDirectorRecipe\?\./)
  assert.match(appSource, /templateRequest=\{flowAiTemplateRequest\}/)
  assert.match(appSource, /display: mainTab === 'flow-ai'[\s\S]*?flowAiTemplateRequest/)
  assert.match(appSource, /key={`flow-ai-workspace-\$\{projectSessionKey\}-\$\{flowAiReloadNonce\}`}/)
  assert.doesNotMatch(appSource, /flowAiReloadNonce}-\$\{flowAiTemplateRequest\?\.requestId/)
  assert.match(appSource, /recipeOnlyMode=\{Boolean\(flowAiTemplateRequest/)
  assert.match(generateCatalogSource, /id: 'anima-lora-factory-director',[\s\S]*?workspace: 'backstage'/)
  assert.match(generateCatalogSource, /templateId: 'anima-lora-dataset'/)
  assert.match(generateCatalogSource, /id: 'sdxl-lora-factory-director',[\s\S]*?workspace: 'backstage'/)
  assert.match(generateCatalogSource, /templateId: 'sdxl-lora-dataset'/)
  assert.match(workspaceSource, /canvas\.actions\.backToBackstage/)
  assert.match(generateWorkspaceSource, /isBackstageSurface \|\| generationMode === 'history' \? 'hidden'/)
  assert.match(generateWorkspaceSource, /setGenerationMode\('backstage'\)[\s\S]*?generate\.mode\.backstage[\s\S]*?setGenerationMode\('history'\)/)
  assert.doesNotMatch(appSource, /mainTab === 'backstage'/)
  assert.match(irodoriVoiceCloneSource, /reference\.chooseFromBrowser/)
  assert.match(irodoriVoiceCloneSource, /onOpenAssetBrowser/)
  assert.match(generateWorkspaceSource, /irodoriAssetBrowserOpen/)
  assert.match(generateWorkspaceSource, /<AssetInputBrowser[\s\S]*?filterType="audio"/)
  assert.match(generateWorkspaceSource, /getSetting\('comfyRootPath'\)/)
  assert.match(generateWorkspaceSource, /pathJoin\(comfyRootPath, 'input'\)/)
  assert.match(generateWorkspaceSource, /listDirectory\(current\.path, \{ includeStats: true \}\)/)
  assert.match(generateWorkspaceSource, /audioExtensionPattern = \/\\\.\(wav\|flac\|mp3/)
  assert.match(generateWorkspaceSource, /importIrodoriReferenceAudioFile\(file\.path\)/)
  assert.match(generateWorkspaceSource, /reference\.comfyInputTab/)
  assert.match(generateWorkspaceSource, /setSelectedAudioAssetId\(asset\?\.id \|\| null\)/)
  assert.match(workspaceSource, /recipeOnlyMode \? 'mx-auto w-full max-w-6xl'/)
  assert.match(workspaceSource, /max-w-6xl/)
})

for (const [templateId, factoryName] of [
  ['anima-lora-dataset', 'Anima LoRA Factory'],
  ['sdxl-lora-dataset', 'SDXL LoRA Factory'],
]) {
  test(`${factoryName} template prepares an eight-angle training flow`, () => {
    assert.match(schemaSource, new RegExp(`id: '${templateId}'`))
    assert.match(schemaSource, /function buildLoraDatasetTemplate/)
    assert.match(schemaSource, /workflowId: 'multi-angles'/)
    assert.match(schemaSource, /width: 1024/)
    assert.match(schemaSource, /height: 1024/)
    assert.match(schemaSource, /label: 'Masked Inpaint Edit \(optional\)'/)
    assert.match(schemaSource, /optionalStage: 'inpaint'/)
    assert.match(schemaSource, /enabled: false/)
    assert.match(schemaSource, /label: 'Inpaint Mask \(optional\)'/)
    assert.match(schemaSource, /label: 'Inpaint Reference \(optional\)'/)
    assert.match(schemaSource, /target: inpaintNode\.id,[\s\S]*?targetHandle: 'in:mask'/)
    assert.match(schemaSource, /source: inpaintNode\.id,[\s\S]*?target: angleNode\.id/)
    assert.match(schemaSource, /folderName: `LoRA Training Sets - \$\{factoryLabel\}`/)
  })

  test(`${factoryName} exposes source and license attribution`, () => {
    assert.match(schemaSource, new RegExp(`'${templateId}': Object\\.freeze`))
    assert.match(schemaSource, /author: 'UNfukashigi'/)
    assert.match(schemaSource, /license: 'Apache License 2\.0 \(factory software\)'/)
    assert.match(schemaSource, /repositoryUrl: 'https:\/\/github\.com\/UNfukashigi\//)
    assert.match(schemaSource, /datasetExport: true/)
    assert.match(schemaSource, /presentation: 'recipe'/)
    assert.match(schemaSource, /recipeKind: 'lora-dataset'/)
  })
}

test('LoRA presets render as a single beginner-facing recipe instead of an editable graph', () => {
  assert.match(workspaceSource, /function LoraDatasetRecipeCanvas/)
  assert.match(workspaceSource, /canvas\.recipe\.characterImage/)
  assert.match(workspaceSource, /canvas\.recipe\.maskedEdit/)
  assert.match(workspaceSource, /canvas\.recipe\.generateTrainingImages/)
  assert.match(workspaceSource, /canvas\.recipe\.resultsPlaceholder/)
  assert.doesNotMatch(workspaceSource, /<optgroup label="Preset recipes">/)
  assert.match(workspaceSource, /FLOW_AI_TEMPLATE_INFO\[template\.id\]\?\.presentation !== 'recipe'/)
  assert.match(workspaceSource, /FLOW_TEMPLATE_CATEGORIES\.map/)
  assert.match(workspaceSource, /activeDocumentDetails\?\.presentation === 'recipe'/)
  assert.match(workspaceSource, /activeDocumentIsRecipe \? \([\s\S]*?<LoraDatasetRecipeCanvas/)
  assert.match(workspaceSource, /\{!activeDocumentIsRecipe && \([\s\S]*?canvas\.nodePalette/)
  assert.match(workspaceSource, /activeDocumentIsRecipe \? t\('canvas\.inspector\.recipeAssets'\) : t\('canvas\.inspector\.title'\)/)
  assert.match(workspaceSource, /canvas\.assets\.assignTo/)
  assert.match(workspaceSource, /const assetBrowserTargetNode = activeDocumentIsRecipe/)
  assert.match(workspaceSource, /\{!activeDocumentIsRecipe && selectedNode && \(/)
  assert.match(workspaceSource, /if \(activeDocumentIsRecipe\) return undefined/)
})

test('document information control and dismissible modal are rendered', () => {
  assert.match(workspaceSource, /aria-label={`Information about \$\{documentInfo\.title\}`}/)
  assert.match(workspaceSource, /onMouseDown=\{\(\) => setInformationDocumentId\(null\)\}/)
  assert.match(workspaceSource, /canvas\.information\.threeSteps/)
  assert.match(workspaceSource, /canvas\.information\.chooseDesignSet/)
  assert.match(workspaceSource, /canvas\.information\.exportAgain/)
  assert.match(workspaceSource, /canvas\.information\.launchFactory/)
  assert.match(workspaceSource, /canvas\.information\.externalTrainingHelp/)
})

test('LoRA documents expose and automatically open the post-generation training guide', () => {
  assert.match(workspaceSource, /canvas\.recipeInfo/)
  assert.match(workspaceSource, /activeDocumentCreatesLoraDataset && importedCount > 0/)
  assert.match(workspaceSource, /setInformationDocumentId\(activeDocument\.id\)/)
  assert.match(workspaceSource, /canvas\.recipe\.automaticExport/)
  assert.doesNotMatch(workspaceSource, /if \(copiedCount > 0\) setInformationDocumentId\(null\)/)
})

test('LoRA guide accepts an existing image dataset before the angle flow is complete', () => {
  assert.match(workspaceSource, /hasCompleteGeneratedAngleSet = generatedAngleAssetIds\.length >= 8/)
  assert.match(workspaceSource, /Choose an existing \$\{factoryLabel\} image dataset folder/)
  assert.match(workspaceSource, /if \(!hasCompleteGeneratedAngleSet\) \{[\s\S]*?setLoraDatasetExportPath\(destination\)/)
  assert.match(workspaceSource, /setLoraDatasetStatus\('existing'\)/)
  assert.doesNotMatch(workspaceSource, /Run the eight-angle flow first, then export/)
  assert.match(workspaceSource, /canvas\.recipe\.factoryHandoff/)
  assert.match(workspaceSource, /canvas\.recipe\.chooseExistingDataset/)
  assert.match(workspaceSource, /handleChooseExistingLoraDataset/)
  assert.match(workspaceSource, /onLaunchFactory=\{\(\) => \{ void handleLaunchInstalledFactory\(activeDocument\) \}\}/)
  assert.match(workspaceSource, /disabled=\{!datasetReady \|\| isLaunchingFactory\}/)
  assert.match(workspaceSource, /canvas\.recipe\.datasetReady/)
})

test('LoRA recipe requires a Step 1 Design Set folder and exports automatically after generation', () => {
  assert.match(workspaceSource, /canvas\.recipe\.designSetFolder/)
  assert.match(workspaceSource, /canvas\.recipe\.chooseOutputRequired/)
  assert.match(workspaceSource, /disabled=\{isRunning \|\| isExportingDataset[\s\S]*?!datasetPath/)
  assert.match(workspaceSource, /handleChooseLoraDatasetOutput/)
  assert.match(workspaceSource, /exportLoraAssetsToDirectory/)
  assert.match(workspaceSource, /function ensureDatasetImageExtension/)
  assert.match(workspaceSource, /mimeExtension \|\| 'png'/)
  assert.match(workspaceSource, /ensureDatasetImageExtension\(sanitizedSourceName, sourcePath, asset\)/)
  assert.match(workspaceSource, /destination: loraDatasetExportPath/)
  assert.match(workspaceSource, /Design Set ready: \$\{automaticExportResult\.destination\}/)
  assert.match(workspaceSource, /setLoraDatasetStatus\('output-selected'\)/)
  assert.match(workspaceSource, /setLoraDatasetStatus\('ready'\)/)
  assert.match(workspaceSource, /\['ready', 'existing'\]\.includes\(loraDatasetStatus\)/)
})

test('exported LoRA dataset path is handed off to both external Factory GUIs', () => {
  assert.match(workspaceSource, /datasetPath,/)
  assert.match(workspaceSource, /datasetPath: automaticExportResult\.destination/)
  assert.match(workspaceSource, /datasetStatus: 'ready'/)
  assert.match(workspaceSource, /await handleLaunchInstalledFactory\(snapshot/)
  assert.match(workspaceSource, /await handleLaunchInstalledFactory\(document, \{ datasetPath: destination, datasetStatus: 'existing' \}\)/)
  assert.match(workspaceSource, /Opening the Factory with the dataset, model, and ComfyUI LoRA output paths/)
  assert.match(electronMainSource, /prepareLoraFactoryDatasetHandoff/)
  assert.match(electronMainSource, /lumeweft-dataset-handoff\.json/)
  assert.match(electronMainSource, /'anima_factory_'/)
  assert.match(electronMainSource, /'sdxl_factory_saved_'/)
  assert.match(electronMainSource, /'dataset-path'/)
  assert.match(electronMainSource, /index\.html\.lumeweft-backup/)
  assert.match(electronMainSource, /datasetHandoff\.applied/)
})

test('LoRA Factory reuses the existing flow base model and downloads only missing roles', () => {
  assert.match(communityModelBrowserSource, /setSetting\?\.\('animaBaseDiffusionModel', selected\)/)
  assert.match(communityModelBrowserSource, /setSetting\?\.\('sdxlBaseCheckpoint', selected\)/)
  assert.match(workspaceSource, /getSetting\('animaBaseDiffusionModel'\)/)
  assert.match(workspaceSource, /chooseCivitaiAnimaDiffusionModel\(baseChoices, getComfyModelBasename\(savedBase\)\)/)
  assert.match(workspaceSource, /chooseCivitaiLoraBaseCheckpoint\(baseChoices, 'SDXL', getComfyModelBasename\(savedBase\)\)/)
  assert.match(workspaceSource, /checkWorkflowSetupFiles/)
  assert.match(workspaceSource, /missingRecipes/)
  assert.match(workspaceSource, /installWorkflowSetup/)
  assert.match(workspaceSource, /modelPaths,/)
  assert.match(workspaceSource, /outputDirectory: preparedPaths\.outputDirectory/)
  assert.match(electronMainSource, /'model-path'/)
  assert.match(electronMainSource, /'vae-path'/)
  assert.match(electronMainSource, /'qwen-path'/)
  assert.match(electronMainSource, /'output-dir'/)
  assert.match(electronMainSource, /pathsByKey\.get\(normalizeModelSearchKey\('loras'\)\)/)
  assert.match(electronMainSource, /path\.join\(validation\.modelsPath, 'loras'\)/)
  assert.match(electronMainSource, /loraOutputPath/)
  assert.match(electronMainSource, /storagePrefix \+ fieldId/)
})

test('LoRA Factory execution folders are saved in Settings and reused without a launch-time picker', () => {
  assert.match(settingsSource, /ANIMA_LORA_FACTORY_ROOT_SETTING_KEY = 'animaLoraFactoryRootPath'/)
  assert.match(settingsSource, /SDXL_LORA_FACTORY_ROOT_SETTING_KEY = 'sdxlLoraFactoryRootPath'/)
  assert.match(settingsSource, /settings\.paths\.loraFactories/)
  assert.match(settingsSource, /validateLoraFactoryRoot/)
  assert.match(settingsSource, /setSetting\?\.\(ANIMA_LORA_FACTORY_ROOT_SETTING_KEY/)
  assert.match(settingsSource, /setSetting\?\.\(SDXL_LORA_FACTORY_ROOT_SETTING_KEY/)
  assert.match(workspaceSource, /LORA_FACTORY_ROOT_SETTING_KEYS/)
  assert.match(workspaceSource, /electron\.getSetting\(LORA_FACTORY_ROOT_SETTING_KEYS\[factoryType\]\)/)
  assert.match(workspaceSource, /canvas\.actions\.openFactorySettings/)
  assert.match(workspaceSource, /focusTarget: 'lora-factories'/)
  assert.match(appSource, /onOpenSettings=\{\(section, options\) => openSettingsModal\(section, options\)\}/)
  assert.match(appSource, /initialFocusTarget=\{settingsFocusTarget\}/)
  assert.match(settingsSource, /id="settings-lora-factories"/)
  assert.match(settingsSource, /scrollIntoView\(\{ behavior: 'smooth', block: 'center' \}\)/)
  assert.match(electronMainSource, /loraFactory:validateRoot/)
  assert.match(electronPreloadSource, /validateLoraFactoryRoot/)
})

test('image input nodes expose a project-owning file loader', () => {
  assert.match(workspaceSource, /canvas\.assets\.chooseFromFile/)
  assert.match(workspaceSource, /canvas\.assets\.loadFromFile/)
  assert.match(workspaceSource, /importAsset\(currentProjectHandle, sourcePath,[\s\S]*?: 'images'\)/)
  assert.match(workspaceSource, /onPickImage: handlePickNodeImage/)
  assert.match(workspaceSource, /onClearProjectAsset: handleClearNodeProjectAsset/)
  assert.match(workspaceSource, /canvas\.assets\.clearAssigned/)
  assert.match(workspaceSource, /assetId: '',[\s\S]*?assetLabel: ''/)
  assert.match(workspaceSource, /currentPreviewAsset\?\.id === clearedAssetId/)
})

test('image input preview opens an existing project asset picker', () => {
  assert.match(workspaceSource, /canvas\.assets\.chooseExisting/)
  assert.match(workspaceSource, /canvas\.assets\.selectExisting/)
  assert.match(workspaceSource, /onChooseProjectAsset: handleChooseNodeProjectAsset/)
  assert.match(workspaceSource, /imageInputAssetOptions: imageInputAssets/)
  assert.match(workspaceSource, /styleAssetOptions: styleAssets/)
  assert.match(workspaceSource, /maskAssetOptions: maskAssets/)
  assert.match(workspaceSource, /asset\.type === 'image' \|\| asset\.type === 'video'/)
})

test('LoRA outputs create their nested Assets folders with the current folder API', () => {
  assert.match(schemaSource, /folderName: `LoRA Training Sets - \$\{factoryLabel\}`/)
  assert.match(schemaSource, /numberedRunFolders: true/)
  assert.match(runtimeSource, /function createNextNumberedAssetFolder/)
  assert.match(runtimeSource, /String\(highestExistingNumber \+ 1\)\.padStart\(3, '0'\)/)
  assert.match(runtimeSource, /NUMBERED_RUN_FOLDER_TEMPLATE_IDS\.has/)
  assert.match(runtimeSource, /function documentUsesNumberedRunFolders/)
  assert.match(runtimeSource, /node\?\.data\?\.numberedRunFolders === true/)
  assert.match(runtimeSource, /documentUsesNumberedRunFolders\(workingDocument\)/)
  assert.match(runtimeSource, /assetsState\.addFolder\(\{ name: segment, parentId \}\)/)
  assert.match(runtimeSource, /assetsState\.addFolder\(\{ name: runFolderName, parentId \}\)/)
  assert.doesNotMatch(runtimeSource, /assetsState\.addFolder\(segment, parentId\)/)
  assert.match(runtimeSource, /subfolderSegments: outputTarget\?\.folderSegments \|\| \[\]/)
  assert.match(fileSystemSource, /export const importAsset = async \(projectDir, file, category = 'video', options = \{\}\)/)
  assert.match(fileSystemSource, /pathJoin\(projectDir, 'assets', category, \.\.\.subfolderSegments\)/)
})

test('Assets grid folders expose a direct confirmed delete action', () => {
  assert.match(assetsPanelSource, /aria-label=\{`Delete folder \$\{folder\.name\}`\}/)
  assert.match(assetsPanelSource, /await handleDeleteFolder\(folder\.id, folder\.name\)/)
  assert.match(assetsPanelSource, /title: 'Delete folder\?'/)
})

test('CANVAS inspector includes a folder-aware project Asset Browser', () => {
  assert.match(workspaceSource, /canvas\.assets\.browser/)
  assert.match(workspaceSource, /canvas\.assets\.search/)
  assert.match(workspaceSource, /assetBrowserBreadcrumbs/)
  assert.match(workspaceSource, /setAssetBrowserFolderId\(folder\.id\)/)
  assert.match(workspaceSource, /if \(canAssignToSelectedNode\) \{\s*handleChooseNodeProjectAsset\(assetBrowserTargetNode\.id, asset\.id\)/)
  assert.match(workspaceSource, /<img src=\{posterUrl\} alt="" className="h-full w-full object-contain" \/>/)
  assert.match(workspaceSource, /onDoubleClick=\{asset\.type === 'image' \|\| asset\.type === 'mask' \? \(\) => setOriginalImageAsset\(asset\) : undefined\}/)
  assert.match(workspaceSource, /max-h-\[calc\(100vh-7rem\)\] max-w-\[calc\(100vw-3rem\)\] overflow-auto/)
  assert.match(workspaceSource, /className="block h-auto w-auto max-w-none"/)
  assert.match(workspaceSource, /onMouseDown=\{\(\) => setOriginalImageAsset\(null\)\}/)
  assert.match(workspaceSource, /canvas\.assets\.useIn/)
  assert.match(workspaceSource, /handleChooseNodeProjectAsset\(assetBrowserTargetNode\.id, asset\.id\)/)
  assert.match(workspaceSource, /onContextMenu=\{\(event\) => void handleRevealAssetInFileManager\(event, asset\)\}/)
  assert.match(workspaceSource, /revealAssetInFileManager\(asset\)/)
  assert.match(workspaceSource, /canvas\.assets\.refresh/)
  assert.match(workspaceSource, /getRecordedAbsolutePath\(asset\)/)
  assert.match(workspaceSource, /electron\.pathJoin\(currentProjectHandle, recordedPath\)/)
  assert.match(workspaceSource, /missingAssetIds\.forEach\(\(assetId\) => removeAsset\(assetId\)\)/)
  assert.match(workspaceSource, /The assigned local file was removed outside Lumeweft/)
  assert.match(workspaceSource, /canvas\.assets\.useIn/)
})

test('CANVAS exposes a collapsible live console for flow and LoRA Factory processing', () => {
  assert.match(workspaceSource, /canvas\.console\.title/)
  assert.match(workspaceSource, /setIsProcessConsoleOpen\(\(current\) => !current\)/)
  assert.match(workspaceSource, /onLoraFactoryProcessEvent/)
  assert.match(workspaceSource, /appendProcessConsole/)
  assert.match(workspaceSource, /message: `Starting \$\{activeDocument\.label/)
  assert.match(electronPreloadSource, /onLoraFactoryProcessEvent: \(cb\) =>/)
  assert.match(electronPreloadSource, /ipcRenderer\.on\('loraFactory:processEvent'/)
  assert.match(electronMainSource, /stdio: \['ignore', 'pipe', 'pipe'\]/)
  assert.match(electronMainSource, /child\.stdout\?\.on\('data'/)
  assert.match(electronMainSource, /child\.stderr\?\.on\('data'/)
  assert.match(electronMainSource, /kind: 'exit'/)
})

test('optional LoRA Inpaint bypasses cleanly and composites only the white mask area when enabled', () => {
  assert.match(workspaceSource, /canvas\.recipe\.useMaskedInpaint/)
  assert.match(workspaceSource, /enabled: event\.target\.checked/)
  assert.match(runtimeSource, /optionalStage === 'inpaint' && liveNode\?\.data\?\.enabled !== true/)
  assert.match(runtimeSource, /outputAssetIds: \[passthroughAsset\.id\]/)
  assert.match(runtimeSource, /maskImage: context\.maskFilename/)
  assert.match(comfyuiSource, /class_type: 'ImageToMask'/)
  assert.match(comfyuiSource, /class_type: 'ImageCompositeMasked'/)
  assert.match(comfyuiSource, /mask: \['canvas_inpaint_mask', 0\]/)
  assert.match(schemaSource, /function upgradeLegacyLoraInpaintStage/)
})

test('Workflow Setup highlights the dependency source requested by CANVAS', () => {
  assert.match(workspaceSource, /workflowIds: \[selectedNode\.data\.workflowId\]/)
  assert.match(appSource, /workflowSetupFocusIds=\{workflowSetupFocusIds\}/)
  assert.match(settingsSource, /focusWorkflowIds=\{workflowSetupFocusIds\}/)
  assert.match(workflowSetupSource, /focusedWorkflowIdSet\.has\(result\.workflowId\)/)
  assert.match(workflowSetupSource, /border-red-500 ring-2 ring-red-500\/35/)
  assert.match(workflowSetupSource, /highlightDependencies=\{isFocusedWorkflow\}/)
  assert.match(workflowSetupSource, /scrollIntoView\?\.\(\{ behavior: 'smooth', block: 'center' \}\)/)
})
