import { TOPAZ_VIDEO_UPSCALE_WORKFLOW_ID } from './topazVideoUpscaleConfig'
import {
  CUSTOM_GENERATE_IMAGE_WORKFLOW_ID,
  CUSTOM_GENERATE_VIDEO_WORKFLOW_ID,
} from './generateWorkspaceConfig'
import { getImportedManifestById, getImportedManifestByWorkflowId } from './importedWorkflowRegistry'

const WORKFLOW_ASSET_BASE = (() => {
  const rawBase = typeof import.meta !== 'undefined' && import.meta.env?.BASE_URL
    ? String(import.meta.env.BASE_URL)
    : '/'
  return rawBase.endsWith('/') ? rawBase : `${rawBase}/`
})()

const cover = (filename) => `${WORKFLOW_ASSET_BASE}workflows/setup-covers/${filename}`

export const GENERATE_WORKFLOW_MODES = Object.freeze({
  generate: 'generate',
  create: 'create',
})

export const GENERATE_WORKFLOW_ROUTES = Object.freeze({
  local: 'local',
  cloud: 'cloud',
  custom: 'custom',
  // Live browse of ComfyUI's official template catalog (no local manifests).
  templates: 'templates',
  community: 'community',
})

export const GENERATE_WORKFLOW_CATEGORY_LABELS = Object.freeze({
  all: 'All',
  image: 'Image',
  video: 'Video',
  'image-to-video': 'Image to Video (I2V)',
  'text-to-video': 'Text to Video (T2V)',
  'text-to-image': 'Text to Image (T2I)',
  'image-edit': 'Image to Image (I2I)',
  'video-tools': 'Video Tools',
  audio: 'Audio',
  utility: 'Utility',
  create: 'Create',
})

export const GENERATE_WORKFLOW_FILTERS = Object.freeze([
  { id: 'all', label: 'All' },
  { id: 'image-to-video', label: 'Image to Video (I2V)' },
  { id: 'text-to-video', label: 'Text to Video (T2V)' },
  { id: 'text-to-image', label: 'Text to Image (T2I)' },
  { id: 'image-edit', label: 'Image to Image (I2I)' },
  { id: 'video-tools', label: 'Video Tools' },
  { id: 'audio', label: 'Audio' },
  { id: 'utility', label: 'Utility' },
])

const field = (id, overrides = {}) => ({ id, ...overrides })

const videoFields = Object.freeze([
  field('asset', { label: 'Reference image', type: 'asset', assetType: 'image' }),
  field('prompt', { label: 'Prompt', type: 'textarea' }),
  field('duration', { label: 'Duration', type: 'duration' }),
  field('resolution', { label: 'Resolution', type: 'resolution' }),
  field('fps', { label: 'FPS', type: 'fps' }),
  field('seed', { label: 'Seed', type: 'seed' }),
])

const audioConditionedVideoFields = Object.freeze([
  field('asset', { label: 'Reference image', type: 'asset', assetType: 'image' }),
  field('audioAsset', {
    label: 'Conditioning audio',
    type: 'assetSelect',
    assetType: 'audio',
    helper: 'Choose the song, voice, or dialogue clip that should drive the motion/audio conditioning.',
  }),
  field('prompt', { label: 'Prompt', type: 'textarea' }),
  field('duration', { label: 'Duration', type: 'duration' }),
  field('resolution', { label: 'Resolution', type: 'resolution' }),
  field('fps', { label: 'FPS', type: 'fps' }),
  field('seed', { label: 'Seed', type: 'seed' }),
])

const videoUtilityFields = Object.freeze([
  field('asset', { label: 'Input video', type: 'asset', assetType: 'video' }),
  field('interpolationMultiplier', { label: 'Frame multiplier', type: 'interpolationMultiplier' }),
  field('enableFpsMultiplier', {
    label: 'Multiply output FPS',
    type: 'toggle',
    helper: 'When enabled, the output FPS is multiplied along with the frames. Leave off to keep the original playback speed.',
  }),
])

const textToVideoFields = Object.freeze([
  field('prompt', { label: 'Prompt', type: 'textarea' }),
  field('duration', { label: 'Duration', type: 'duration' }),
  field('resolution', { label: 'Resolution', type: 'resolution' }),
  field('fps', { label: 'FPS', type: 'fps' }),
  field('seed', { label: 'Seed', type: 'seed' }),
])

const firstLastFrameVideoFields = Object.freeze([
  field('firstFrameAsset', {
    label: 'First frame',
    type: 'assetSelect',
    assetType: 'image',
    required: true,
    helper: 'Choose the starting image for the video.',
  }),
  field('lastFrameAsset', {
    label: 'Last frame',
    type: 'assetSelect',
    assetType: 'image',
    required: true,
    helper: 'Choose the ending image Seedance should animate toward.',
  }),
  field('prompt', { label: 'Prompt', type: 'textarea' }),
  field('duration', { label: 'Duration', type: 'duration' }),
  field('resolution', { label: 'Resolution', type: 'resolution' }),
  field('seed', { label: 'Seed', type: 'seed' }),
])

const referenceToVideoFields = Object.freeze([
  field('referenceImage1', {
    label: 'Reference image 1',
    type: 'assetSelect',
    assetType: 'image',
    required: true,
    helper: 'Main identity/style reference.',
  }),
  field('referenceImage2', { label: 'Reference image 2', type: 'assetSelect', assetType: 'image' }),
  field('referenceImage3', { label: 'Reference image 3', type: 'assetSelect', assetType: 'image' }),
  field('referenceImage4', { label: 'Reference image 4', type: 'assetSelect', assetType: 'image' }),
  field('prompt', { label: 'Prompt', type: 'textarea' }),
  field('duration', { label: 'Duration', type: 'duration' }),
  field('resolution', { label: 'Resolution', type: 'resolution' }),
  field('seed', { label: 'Seed', type: 'seed' }),
])

const miniReferenceToVideoFields = Object.freeze([
  field('referenceImage1', {
    label: 'Shot reference',
    type: 'assetSelect',
    assetType: 'image',
    required: true,
    helper: 'Primary composition and identity reference.',
  }),
  field('referenceImage2', { label: 'Reference image 2', type: 'assetSelect', assetType: 'image' }),
  field('referenceImage3', { label: 'Reference image 3', type: 'assetSelect', assetType: 'image' }),
  field('referenceImage4', { label: 'Reference image 4', type: 'assetSelect', assetType: 'image' }),
  field('referenceVideo1', {
    label: 'Audio-guide video',
    type: 'assetSelect',
    assetType: 'video',
    required: true,
    helper: 'Use a black video carrying the exact song segment for performance timing.',
  }),
  field('prompt', { label: 'Prompt', type: 'textarea' }),
  field('duration', { label: 'Duration', type: 'duration' }),
  field('resolution', { label: 'Resolution', type: 'resolution' }),
  field('seed', { label: 'Seed', type: 'seed' }),
])

const minimaxH3ReferenceToVideoFields = Object.freeze([
  field('referenceImage1', {
    label: 'Reference frame',
    type: 'assetSelect',
    assetType: 'image',
    required: true,
    helper: 'Exact first-frame identity, composition, wardrobe, and material reference.',
  }),
  field('referenceAudio1', {
    label: 'Performance audio',
    type: 'assetSelect',
    assetType: 'audio',
    required: true,
    helper: 'Exact audio segment used for performance and lip-sync timing.',
  }),
  field('prompt', { label: 'Prompt', type: 'textarea' }),
  field('duration', { label: 'Duration', type: 'duration' }),
  field('resolution', { label: 'Resolution', type: 'resolution' }),
  field('seed', { label: 'Seed', type: 'seed' }),
])

const imageFields = Object.freeze([
  field('prompt', { label: 'Prompt', type: 'textarea' }),
  field('imageResolution', { label: 'Image size', type: 'imageResolution' }),
  field('seed', { label: 'Seed', type: 'seed' }),
])

const imageEditFields = Object.freeze([
  field('asset', { label: 'Reference image', type: 'asset', assetType: 'image' }),
  field('prompt', { label: 'Edit instruction', type: 'textarea' }),
  field('imageResolution', { label: 'Image size', type: 'imageResolution' }),
  field('seed', { label: 'Seed', type: 'seed' }),
])

const customImageFields = Object.freeze([
  field('customWorkflow', { label: 'Custom workflow', type: 'customWorkflow', customKind: 'image' }),
])

const customVideoFields = Object.freeze([
  field('customWorkflow', { label: 'Custom workflow', type: 'customWorkflow', customKind: 'video' }),
  field('customInputImage', {
    label: 'Input image',
    type: 'assetSelect',
    assetType: 'image',
    helper: 'Shown because this graph keeps VELORN_INPUT_IMAGE.',
  }),
  field('customAudioAsset', {
    label: 'Audio',
    type: 'assetSelect',
    assetType: 'audio',
    helper: 'Shown because this graph keeps VELORN_AUDIO.',
  }),
  field('prompt', { label: 'Prompt', type: 'textarea' }),
  field('resolution', { label: 'Size input', type: 'resolution' }),
  field('fps', { label: 'FPS input', type: 'fps' }),
  field('duration', { label: 'Duration input', type: 'duration' }),
  field('seed', { label: 'Seed', type: 'seed' }),
])

const multiAngleFields = Object.freeze([
  field('asset', { label: 'Reference image', type: 'asset', assetType: 'image' }),
  field('seed', { label: 'Seed', type: 'seed' }),
])

const audioFields = Object.freeze([
  field('musicTags', { label: 'Style tags', type: 'textarea', rows: 2 }),
  field('lyrics', { label: 'Lyrics', type: 'textarea', rows: 4 }),
  field('musicDuration', { label: 'Duration', type: 'musicDuration' }),
])

const videoToAudioFields = Object.freeze([
  field('asset', { label: 'Input video', type: 'asset', assetType: 'video' }),
  field('prompt', { label: 'Music direction', type: 'textarea', rows: 3 }),
  field('seed', { label: 'Seed', type: 'seed' }),
])

const topazVideoEnhanceFields = Object.freeze([
  field('asset', { label: 'Input video', type: 'asset', assetType: 'video' }),
])

const utilityFields = Object.freeze([
  field('asset', { label: 'Input media', type: 'asset', assetType: 'image' }),
  field('prompt', { label: 'Instruction', type: 'textarea' }),
])

export const GENERATE_WORKFLOW_CATALOG = Object.freeze([
  {
    id: 'ltx23-i2v',
    workflowId: 'ltx23-i2v',
    title: 'Image to Video (I2V) — LTX 2.3',
    description: 'Animate a reference image with local LTX 2.3.',
    subtitle: 'Local cinematic image-to-video',
    mode: 'generate',
    route: 'local',
    category: 'image-to-video',
    provider: 'Local',
    cover: cover('ltx23-i2v.webp'),
    badge: 'Local',
    runtimeLabel: '24GB+ recommended',
    needsImage: true,
    outputType: 'video',
    fields: videoFields,
    runnable: true,
    tags: ['ltx', 'i2v', 'video', 'local'],
  },
  {
    id: 'ltx23-ia2v',
    workflowId: 'ltx23-ia2v',
    title: 'Image + Audio to Video (IA2V) — LTX 2.3',
    description: 'Animate a reference image with LTX 2.3 audio conditioning.',
    subtitle: 'Local audio-conditioned image-to-video',
    mode: 'generate',
    route: 'local',
    category: 'image-to-video',
    provider: 'Local',
    cover: cover('ltx23-ia2v.mp4'),
    badge: 'Audio',
    runtimeLabel: '24GB+ recommended',
    needsImage: true,
    requiresAudio: true,
    inputAssetType: 'image',
    outputType: 'video',
    fields: audioConditionedVideoFields,
    runnable: true,
    tags: ['ltx', 'ia2v', 'audio', 'video', 'local'],
  },
  {
    id: 'wan22-i2v',
    workflowId: 'wan22-i2v',
    title: 'Image to Video (I2V) — WAN 2.2',
    description: 'Animate an image with WAN 2.2.',
    subtitle: 'Local natural motion',
    mode: 'generate',
    route: 'local',
    category: 'image-to-video',
    provider: 'Local',
    cover: cover('wan22-i2v.webp'),
    badge: 'Local',
    runtimeLabel: '24GB+ recommended',
    needsImage: true,
    outputType: 'video',
    fields: videoFields,
    runnable: true,
    tags: ['wan', 'i2v', 'video', 'local'],
  },
  {
    id: 'ltx23-t2v',
    workflowId: 'ltx23-t2v',
    title: 'Text to Video (T2V) — LTX 2.3',
    description: 'Generate video directly from a prompt with local LTX 2.3.',
    subtitle: 'Local cinematic text-to-video',
    mode: 'generate',
    route: 'local',
    category: 'text-to-video',
    provider: 'Local',
    cover: cover('ltx23-t2v.webp'),
    badge: 'Local',
    runtimeLabel: '24GB+ recommended',
    needsImage: false,
    outputType: 'video',
    fields: textToVideoFields,
    runnable: true,
    tags: ['ltx', 'text to video', 'video', 'local'],
  },
  {
    id: 'wan22-t2v',
    workflowId: 'wan22-t2v',
    title: 'Text to Video (T2V) — WAN 2.2',
    description: 'Generate video directly from a prompt with local WAN 2.2.',
    subtitle: 'Local text-to-video motion',
    mode: 'generate',
    route: 'local',
    category: 'text-to-video',
    provider: 'Local',
    cover: cover('wan22-t2v.webp'),
    badge: 'Local',
    runtimeLabel: '24GB+ recommended',
    needsImage: false,
    outputType: 'video',
    fields: textToVideoFields,
    runnable: true,
    tags: ['wan', 'text to video', 'video', 'local'],
  },
  {
    id: 'multi-angles',
    workflowId: 'multi-angles',
    title: 'Multiple Angles (Characters)',
    description: 'Generate a set of character camera angles from one image.',
    subtitle: 'Character angle sheet',
    mode: 'generate',
    route: 'local',
    category: 'image-edit',
    provider: 'Local',
    cover: cover('multi-angles.webp'),
    badge: '8 angles',
    runtimeLabel: 'Image workflow',
    needsImage: true,
    outputType: 'image',
    fields: multiAngleFields,
    runnable: true,
    tags: ['angles', 'character', 'image'],
  },
  {
    id: 'multi-angles-scene',
    workflowId: 'multi-angles-scene',
    title: 'Multiple Angles (Scenes)',
    description: 'Generate a set of scene camera angles from one image.',
    subtitle: 'Scene angle sheet',
    mode: 'generate',
    route: 'local',
    category: 'image-edit',
    provider: 'Local',
    cover: cover('multi-angles-scene.webp'),
    badge: '8 angles',
    runtimeLabel: 'Image workflow',
    needsImage: true,
    outputType: 'image',
    fields: multiAngleFields,
    runnable: true,
    tags: ['angles', 'scene', 'image'],
  },
  {
    id: 'image-edit',
    workflowId: 'image-edit',
    title: 'Image Edit',
    description: 'Edit an image with a simple natural-language instruction.',
    subtitle: 'Qwen image edit',
    mode: 'generate',
    route: 'local',
    category: 'image-edit',
    provider: 'Local',
    cover: cover('qwen-image-edit.png'),
    badge: 'Edit',
    runtimeLabel: 'Image workflow',
    needsImage: true,
    outputType: 'image',
    fields: imageEditFields,
    runnable: true,
    tags: ['qwen', 'edit', 'image'],
  },
  {
    id: 'longcat-image-edit',
    workflowId: 'longcat-image-edit',
    title: 'LongCat Image Edit',
    description: 'Edit a reference image with a local LongCat image-edit model.',
    subtitle: 'Local LongCat edit',
    mode: 'generate',
    route: 'local',
    category: 'image-edit',
    provider: 'Local',
    cover: cover('longcat-image-edit.png'),
    badge: 'Edit',
    runtimeLabel: 'Local GPU',
    needsImage: true,
    inputAssetType: 'image',
    outputType: 'image',
    fields: imageEditFields,
    runnable: true,
    tags: ['longcat', 'edit', 'image', 'local'],
  },
  {
    id: 'z-image-turbo',
    workflowId: 'z-image-turbo',
    title: 'Text to Image (Z Image Turbo)',
    description: 'Fast local text-to-image generation.',
    subtitle: 'Fast local stills',
    mode: 'generate',
    route: 'local',
    category: 'text-to-image',
    provider: 'Local',
    cover: cover('z-image-turbo.webp'),
    badge: 'Turbo',
    runtimeLabel: 'Fast stills',
    needsImage: false,
    outputType: 'image',
    fields: imageFields,
    runnable: true,
    tags: ['z image', 'turbo', 'text to image'],
  },
  {
    id: 'longcat-text-to-image',
    workflowId: 'longcat-text-to-image',
    title: 'Text to Image (LongCat)',
    description: 'Generate still images with a local LongCat image model.',
    subtitle: 'Local LongCat stills',
    mode: 'generate',
    route: 'local',
    category: 'text-to-image',
    provider: 'Local',
    cover: cover('longcat-text-to-image.png'),
    badge: 'Local',
    runtimeLabel: 'Local GPU',
    needsImage: false,
    outputType: 'image',
    fields: imageFields,
    runnable: true,
    tags: ['longcat', 'text to image', 'local'],
  },
  {
    id: 'ernie-image-turbo',
    workflowId: 'ernie-image-turbo',
    title: 'Text to Image (Ernie Turbo)',
    description: 'Generate fast still images with the local Ernie Image Turbo workflow.',
    subtitle: 'Local Ernie stills',
    mode: 'generate',
    route: 'local',
    category: 'text-to-image',
    provider: 'Local',
    cover: cover('ernie-image-turbo.webp'),
    badge: 'Turbo',
    runtimeLabel: 'Local GPU',
    needsImage: false,
    outputType: 'image',
    fields: imageFields,
    runnable: true,
    tags: ['ernie', 'turbo', 'text to image', 'local'],
  },
  {
    id: 'flux2-text-to-image',
    workflowId: 'flux2-text-to-image',
    title: 'Text to Image (Flux 2)',
    description: 'Generate still images with a local Flux 2 workflow.',
    subtitle: 'Local Flux 2 stills',
    mode: 'generate',
    route: 'local',
    category: 'text-to-image',
    provider: 'Local',
    cover: cover('flux2-text-to-image.png'),
    badge: 'Local',
    runtimeLabel: 'Local GPU',
    needsImage: false,
    outputType: 'image',
    fields: imageFields,
    runnable: true,
    tags: ['flux 2', 'text to image', 'local'],
  },
  {
    id: 'frame-interpolation',
    workflowId: 'frame-interpolation',
    title: 'Frame Interpolation',
    description: 'Add in-between frames to make video motion smoother.',
    subtitle: 'Local video frame interpolation',
    mode: 'generate',
    route: 'local',
    category: 'video-tools',
    provider: 'Local',
    cover: cover('frame-interpolation.webp'),
    badge: 'Utility',
    runtimeLabel: 'Local GPU',
    needsImage: true,
    inputAssetType: 'video',
    outputType: 'video',
    fields: videoUtilityFields,
    runnable: true,
    tags: ['frame interpolation', 'fps', 'video utility', 'local'],
  },
  {
    id: 'music-gen',
    workflowId: 'music-gen',
    title: 'Music Generation',
    description: 'Generate music from style tags and optional lyrics.',
    subtitle: 'Local music generation',
    mode: 'generate',
    route: 'local',
    category: 'audio',
    provider: 'Local',
    cover: cover('music-gen.webp'),
    badge: 'Audio',
    runtimeLabel: 'Audio workflow',
    needsImage: false,
    outputType: 'audio',
    fields: audioFields,
    runnable: true,
    tags: ['music', 'audio', 'lyrics'],
  },
  {
    id: 'kling-o3-i2v',
    workflowId: 'kling-o3-i2v',
    title: 'Kling 3.0: Image to Video (I2V)',
    description: 'Premium cloud image-to-video with Kling O3 Omni.',
    subtitle: 'Premium cloud i2v',
    mode: 'generate',
    route: 'cloud',
    category: 'image-to-video',
    provider: 'Kling',
    cover: cover('kling-o3-i2v.webp'),
    badge: 'Cloud',
    runtimeLabel: 'Requires API key',
    needsImage: true,
    outputType: 'video',
    fields: videoFields,
    runnable: true,
    tags: ['kling', 'cloud', 'i2v'],
  },
  {
    id: 'vidu-q2-i2v',
    workflowId: 'vidu-q2-i2v',
    title: 'Vidu Q2: Image to Video (I2V)',
    description: 'Fast cloud image-to-video for blocking and exploration.',
    subtitle: 'Affordable cloud i2v',
    mode: 'generate',
    route: 'cloud',
    category: 'image-to-video',
    provider: 'Vidu',
    cover: cover('vidu-q2-i2v.webp'),
    badge: 'Cloud',
    runtimeLabel: 'Requires API key',
    needsImage: true,
    outputType: 'video',
    fields: videoFields,
    runnable: true,
    tags: ['vidu', 'cloud', 'i2v'],
  },
  {
    id: 'grok-video-i2v',
    workflowId: 'grok-video-i2v',
    title: 'Grok: Video Generation',
    description: 'Cloud image-to-video with Grok Imagine Video.',
    subtitle: 'xAI cloud video',
    mode: 'generate',
    route: 'cloud',
    category: 'image-to-video',
    provider: 'Grok',
    cover: cover('grok-video-i2v.webp'),
    badge: 'Cloud',
    runtimeLabel: 'Requires API key',
    needsImage: true,
    outputType: 'video',
    fields: videoFields,
    runnable: true,
    tags: ['grok', 'cloud', 'video'],
  },
  {
    id: 'minimax-h3-r2v',
    workflowId: 'minimax-h3-r2v',
    title: 'MiniMax H3: Reference + Audio to Video (R2V)',
    description: 'Generate a premium reference-driven video with native audio-conditioned performance timing.',
    subtitle: 'MiniMax H3 image + audio reference video',
    mode: 'generate',
    route: 'cloud',
    category: 'image-to-video',
    provider: 'MiniMax',
    cover: cover('seedance2-r2v.webp'),
    badge: 'Cloud',
    runtimeLabel: 'Uses Comfy credits',
    needsImage: false,
    outputType: 'video',
    fields: minimaxH3ReferenceToVideoFields,
    runnable: true,
    tags: ['minimax', 'h3', 'reference video', 'audio reference', 'lip sync', 'cloud'],
  },
  {
    id: 'seedance2-t2v',
    workflowId: 'seedance2-t2v',
    title: 'Seedance 2.0: Text to Video (T2V)',
    description: 'Generate cloud video directly from a prompt with ByteDance Seedance 2.0.',
    subtitle: 'ByteDance cloud text-to-video',
    mode: 'generate',
    route: 'cloud',
    category: 'text-to-video',
    provider: 'ByteDance',
    cover: cover('seedance2-t2v.webp'),
    badge: 'Cloud',
    runtimeLabel: 'Requires API key',
    needsImage: false,
    outputType: 'video',
    fields: textToVideoFields,
    runnable: true,
    tags: ['seedance', 'bytedance', 'text to video', 'cloud'],
  },
  {
    id: 'seedance2-mini-t2v',
    workflowId: 'seedance2-mini-t2v',
    title: 'Seedance 2.0 Mini: Text to Video (T2V)',
    description: 'Lower-cost cloud video from a prompt with ByteDance Seedance 2.0 Mini — about half the price of Seedance 2.0 at 720p.',
    subtitle: 'ByteDance budget cloud text-to-video',
    mode: 'generate',
    route: 'cloud',
    category: 'text-to-video',
    provider: 'ByteDance',
    cover: cover('seedance2-t2v.webp'),
    badge: 'Cloud',
    runtimeLabel: 'Requires API key',
    needsImage: false,
    outputType: 'video',
    fields: textToVideoFields,
    runnable: true,
    tags: ['seedance', 'bytedance', 'mini', 'text to video', 'cloud', 'budget'],
  },
  {
    id: 'seedance2-mini-r2v',
    workflowId: 'seedance2-mini-r2v',
    title: 'Seedance 2.0 Mini: Reference + Audio Guide (R2V)',
    description: 'Lower-cost multi-reference video with a video reference for timed puppet or character performance.',
    subtitle: 'ByteDance Mini multi-reference video',
    mode: 'generate',
    route: 'cloud',
    category: 'image-to-video',
    provider: 'ByteDance',
    cover: cover('seedance2-r2v.webp'),
    badge: 'Cloud',
    runtimeLabel: 'Requires API key',
    needsImage: false,
    outputType: 'video',
    fields: miniReferenceToVideoFields,
    runnable: true,
    tags: ['seedance', 'bytedance', 'mini', 'reference video', 'audio guide', 'cloud', 'budget'],
  },
  {
    id: 'seedance2-flf2v',
    workflowId: 'seedance2-flf2v',
    title: 'Seedance 2.0: First/Last Frame to Video (FLF2V)',
    description: 'Animate between a chosen first frame and final frame with Seedance 2.0.',
    subtitle: 'ByteDance cloud transition video',
    mode: 'generate',
    route: 'cloud',
    category: 'image-to-video',
    provider: 'ByteDance',
    cover: cover('seedance2-flf2v.webp'),
    badge: 'Cloud',
    runtimeLabel: 'Requires API key',
    needsImage: false,
    outputType: 'video',
    fields: firstLastFrameVideoFields,
    runnable: true,
    tags: ['seedance', 'bytedance', 'first frame', 'last frame', 'cloud'],
  },
  {
    id: 'seedance2-r2v',
    workflowId: 'seedance2-r2v',
    title: 'Seedance 2.0: Reference to Video (R2V)',
    description: 'Generate video from up to four reference images and a motion prompt.',
    subtitle: 'ByteDance cloud multi-reference video',
    mode: 'generate',
    route: 'cloud',
    category: 'image-to-video',
    provider: 'ByteDance',
    cover: cover('seedance2-r2v.webp'),
    badge: 'Cloud',
    runtimeLabel: 'Requires API key',
    needsImage: false,
    outputType: 'video',
    fields: referenceToVideoFields,
    runnable: true,
    tags: ['seedance', 'bytedance', 'reference video', 'cloud'],
  },
  {
    id: 'nano-banana-2',
    workflowId: 'nano-banana-2',
    title: 'Nano Banana 2: Image Edit',
    description: 'Google/Nano Banana image generation and editing.',
    subtitle: 'Cloud image workflow',
    mode: 'generate',
    route: 'cloud',
    category: 'image-edit',
    provider: 'Google',
    cover: cover('nano-banana-2.webp'),
    badge: 'Cloud',
    runtimeLabel: 'Requires API key',
    needsImage: true,
    outputType: 'image',
    fields: imageEditFields,
    runnable: true,
    tags: ['google', 'nano banana', 'image', 'image edit', 'reference'],
  },
  {
    id: 'gpt-image-2-t2i',
    workflowId: 'gpt-image-2-t2i',
    title: 'GPT Image 2: Text to Image',
    description: 'Generate still images with OpenAI GPT Image 2.',
    subtitle: 'OpenAI cloud image',
    mode: 'generate',
    route: 'cloud',
    category: 'text-to-image',
    provider: 'OpenAI',
    cover: cover('gpt-image-2-t2i.webp'),
    badge: 'Cloud',
    runtimeLabel: 'Requires API key',
    needsImage: false,
    outputType: 'image',
    fields: imageFields,
    runnable: true,
    tags: ['openai', 'gpt image', 'text to image', 'cloud'],
  },
  {
    id: 'gpt-image-2-edit',
    workflowId: 'gpt-image-2-edit',
    title: 'GPT Image 2: Image Edit',
    description: 'Edit a reference image with OpenAI GPT Image 2.',
    subtitle: 'OpenAI cloud image edit',
    mode: 'generate',
    route: 'cloud',
    category: 'image-edit',
    provider: 'OpenAI',
    cover: cover('gpt-image-2-edit.webp'),
    badge: 'Cloud',
    runtimeLabel: 'Requires API key',
    needsImage: true,
    inputAssetType: 'image',
    outputType: 'image',
    fields: imageEditFields,
    runnable: true,
    tags: ['openai', 'gpt image', 'edit', 'cloud'],
  },
  {
    id: 'grok-text-to-image',
    workflowId: 'grok-text-to-image',
    title: 'Grok: Text to Image',
    description: 'Cloud text-to-image with Grok Imagine.',
    subtitle: 'xAI cloud image',
    mode: 'generate',
    route: 'cloud',
    category: 'text-to-image',
    provider: 'Grok',
    cover: cover('grok-text-to-image.webp'),
    badge: 'Cloud',
    runtimeLabel: 'Requires API key',
    needsImage: false,
    outputType: 'image',
    fields: imageFields,
    runnable: true,
    tags: ['grok', 'cloud', 'text to image'],
  },
  {
    id: 'seedream-5-lite-image-edit',
    workflowId: 'seedream-5-lite-image-edit',
    title: 'Seedream 5.0 Lite: Image Edit',
    description: 'Cloud image edit with ByteDance Seedream.',
    subtitle: 'ByteDance image edit',
    mode: 'generate',
    route: 'cloud',
    category: 'image-edit',
    provider: 'ByteDance',
    cover: cover('seedream-5-lite-image-edit.webp'),
    badge: 'Cloud',
    runtimeLabel: 'Requires API key',
    needsImage: true,
    outputType: 'image',
    fields: imageEditFields,
    runnable: true,
    tags: ['seedream', 'bytedance', 'edit'],
  },
  {
    id: TOPAZ_VIDEO_UPSCALE_WORKFLOW_ID,
    workflowId: TOPAZ_VIDEO_UPSCALE_WORKFLOW_ID,
    title: 'Topaz Video Enhance',
    description: 'Cloud video upscaling through Topaz.',
    subtitle: 'Video enhancement',
    mode: 'generate',
    route: 'cloud',
    category: 'video-tools',
    provider: 'Topaz',
    cover: cover('topaz-video-enhance.webp'),
    badge: 'Enhance',
    runtimeLabel: 'Requires API key',
    needsImage: false,
    inputAssetType: 'video',
    outputType: 'video',
    fields: topazVideoEnhanceFields,
    runnable: true,
    tags: ['topaz', 'upscale', 'video'],
  },
  {
    id: 'happyhorse-image-video',
    title: 'HappyHorse: Image to Video',
    description: 'Popular Comfy catalog image-to-video workflow.',
    subtitle: 'Catalog candidate',
    mode: 'generate',
    route: 'cloud',
    category: 'image-to-video',
    provider: 'HappyHorse',
    cover: cover('happyhorse-image-video.webp'),
    badge: 'Preview',
    runtimeLabel: 'Workflow graph needed',
    needsImage: true,
    outputType: 'video',
    fields: videoFields,
    runnable: false,
    tags: ['happyhorse', 'cloud', 'i2v'],
  },
  {
    id: 'sonilo-v2m',
    workflowId: 'sonilo-v2m',
    title: 'Sonilo: Video to Music',
    description: 'Generate music that matches an input video and written direction.',
    subtitle: 'Cloud video-to-music',
    mode: 'generate',
    route: 'cloud',
    category: 'audio',
    provider: 'Sonilo',
    cover: cover('sonilo-v2m.webp'),
    badge: 'Cloud',
    runtimeLabel: 'Requires API key',
    needsImage: true,
    inputAssetType: 'video',
    outputType: 'audio',
    fields: videoToAudioFields,
    runnable: true,
    tags: ['sonilo', 'video to music', 'audio', 'cloud'],
  },
  {
    id: 'custom-image-workflow',
    workflowId: CUSTOM_GENERATE_IMAGE_WORKFLOW_ID,
    title: 'Custom Image Workflow',
    description: 'Bring your own ComfyUI image graph. Velorn runs it from Generate and imports the output image.',
    subtitle: 'Your ComfyUI image graph',
    mode: 'generate',
    route: 'custom',
    category: 'image',
    provider: 'Velorn',
    cover: cover('custom-image-workflow.webp'),
    badge: 'Custom',
    runtimeLabel: 'Graph-dependent',
    needsImage: false,
    inputAssetType: 'image',
    outputType: 'image',
    fields: customImageFields,
    runnable: true,
    // Superseded by the personal workflow library (save from the ComfyUI tab);
    // kept hidden because the Director custom-workflow bridges share plumbing.
    hidden: true,
    tags: ['custom', 'comfyui', 'image', 'image edit', 'text to image'],
  },
  {
    id: 'custom-video-workflow',
    workflowId: CUSTOM_GENERATE_VIDEO_WORKFLOW_ID,
    title: 'Custom Video Workflow',
    description: 'Bring your own ComfyUI video graph. Velorn exposes only the inputs declared by matching endpoint nodes.',
    subtitle: 'Your ComfyUI video graph',
    mode: 'generate',
    route: 'custom',
    category: 'video',
    provider: 'Velorn',
    cover: cover('custom-video-workflow.webp'),
    badge: 'Custom',
    runtimeLabel: 'Graph-dependent',
    needsImage: false,
    inputAssetType: 'image',
    outputType: 'video',
    fields: customVideoFields,
    runnable: true,
    hidden: true,
    tags: ['custom', 'comfyui', 'video', 'image to video', 'text to video', 'audio'],
  },
  {
    id: 'ugc-ad-creator',
    title: 'UGC Creator',
    description: 'Creator-style social ads with hooks, dialogue, product demos, unboxings, try-ons, and editable shot clips.',
    subtitle: 'Creator-style ad',
    mode: 'create',
    route: 'local',
    category: 'create',
    provider: 'Velorn',
    cover: cover('ugc-ad-creator.jpg'),
    coverPosition: '50% center',
    badge: 'Beta',
    runtimeLabel: 'Creator UGC',
    needsImage: false,
    outputType: 'video',
    fields: utilityFields,
    runnable: false,
    tags: ['ugc', 'ad', 'creator', 'testimonial', 'unboxing', 'try on', 'demo', 'create', 'easy mode'],
  },
  {
    id: 'business-ad-creator',
    title: 'Business Ad Creator',
    description: 'Offer-first ads for local businesses, online shops, services, events, and small teams.',
    subtitle: 'Offer to ad',
    mode: 'create',
    route: 'local',
    category: 'create',
    provider: 'Velorn',
    cover: cover('create-ad.jpg'),
    coverPosition: '65% center',
    badge: 'Beta',
    runtimeLabel: 'Small business',
    needsImage: false,
    outputType: 'video',
    fields: utilityFields,
    runnable: false,
    tags: ['ad', 'business', 'local business', 'ecommerce', 'offer', 'create', 'easy mode'],
  },
  {
    id: 'product-ad-easy-mode',
    title: 'Ad Creation',
    description: 'Guided product ad creation with brief, references, script, keyframes, and shot video review.',
    subtitle: 'Brief to ad',
    mode: 'create',
    route: 'local',
    category: 'create',
    provider: 'Velorn',
    cover: cover('create-ad.jpg'),
    coverPosition: '65% center',
    badge: 'Easy',
    runtimeLabel: 'Nano Banana + LTX/WAN',
    needsImage: false,
    outputType: 'video',
    fields: utilityFields,
    runnable: false,
    hidden: true,
    tags: ['ad', 'product', 'create', 'easy mode'],
  },
  {
    id: 'music-video-template',
    title: 'Music Video Creation',
    description: 'Guided music video planning and generation.',
    subtitle: 'Lyrics to shots',
    mode: 'create',
    route: 'local',
    category: 'create',
    provider: 'Velorn',
    cover: cover('create-music-video.jpg'),
    coverPosition: '58% center',
    badge: 'Easy',
    runtimeLabel: 'Lyrics + LTX',
    needsImage: false,
    outputType: 'video',
    fields: audioFields,
    runnable: false,
    tags: ['music video', 'create', 'lyrics', 'easy mode'],
  },
  {
    id: 'short-film-easy-mode',
    title: 'Short Film Creation',
    description: 'Guided short film planning with characters, locations, voices, shot coverage, keyframes, and timeline assembly.',
    subtitle: 'Script to scene coverage',
    mode: 'create',
    route: 'local',
    category: 'create',
    provider: 'Velorn',
    cover: cover('create-short-film.jpg'),
    coverPosition: '50% center',
    badge: 'Easy',
    runtimeLabel: 'Script + voices + LTX',
    needsImage: false,
    outputType: 'video',
    fields: utilityFields,
    runnable: false,
    tags: ['short film', 'film', 'dialogue', 'voices', 'create', 'easy mode'],
  },
  {
    id: 'music-video-template-cloud',
    title: 'Music Video',
    description: 'Guided music video planning with cloud-rendered shots.',
    subtitle: 'Premium cloud music video',
    mode: 'create',
    route: 'cloud',
    category: 'create',
    provider: 'Velorn',
    cover: cover('multi-angles-scene.webp'),
    badge: 'Beta',
    runtimeLabel: 'Uses cloud video APIs',
    needsImage: false,
    outputType: 'video',
    fields: audioFields,
    runnable: false,
    tags: ['music video', 'create', 'lyrics', 'cloud'],
  },
])

export function getWorkflowManifestByWorkflowId(workflowId) {
  return GENERATE_WORKFLOW_CATALOG.find((workflow) => workflow.workflowId === workflowId)
    || getImportedManifestByWorkflowId(workflowId)
}

export function getWorkflowManifestById(id) {
  return GENERATE_WORKFLOW_CATALOG.find((workflow) => workflow.id === id)
    || getImportedManifestById(id)
}
