import { AINVFX_FLUID_MODELS } from './ainvfxFluidConfig.js'
import { VDN_H3_STAGE_FILES } from './vdnH3Config.js'
import { getImportedModelRecipe } from './importedWorkflowRegistry.js'

const COMFY_REGISTRY_URL = 'https://registry.comfy.org'
const HUGGING_FACE_BASE_URL = 'https://huggingface.co'

function hfResolve(repo, relativePath) {
  return `${HUGGING_FACE_BASE_URL}/${repo}/resolve/main/${relativePath}`
}

function hfBlob(repo, relativePath) {
  return `${HUGGING_FACE_BASE_URL}/${repo}/blob/main/${relativePath}`
}

function modelKey(targetSubdir = '', filename = '') {
  return `${String(targetSubdir || '').trim().toLowerCase()}::${String(filename || '').trim().toLowerCase()}`
}

function createModelRecipe({
  filename,
  targetSubdir,
  displayName,
  downloadUrl,
  sourceUrl = '',
  licenseUrl = '',
  sizeBytes = null,
  sha256 = '',
  requiresAccessApproval = false,
  notes = '',
}) {
  return Object.freeze({
    filename,
    targetSubdir,
    displayName,
    downloadUrl,
    sourceUrl,
    licenseUrl,
    sizeBytes: Number.isFinite(sizeBytes) ? Number(sizeBytes) : null,
    sha256: String(sha256 || '').trim().toLowerCase(),
    requiresAccessApproval: requiresAccessApproval === true,
    notes: String(notes || '').trim(),
  })
}

function createAutoNodePack({
  id,
  displayName,
  repoUrl,
  installDirName,
  docsUrl = repoUrl,
  requirementsStrategy = 'requirements-txt',
  notes = '',
  classTypes = [],
}) {
  return Object.freeze({
    id,
    kind: 'auto',
    displayName,
    repoUrl,
    installDirName,
    docsUrl,
    requirementsStrategy,
    notes,
    classTypes: Object.freeze(
      (Array.isArray(classTypes) ? classTypes : [])
        .map((entry) => String(entry || '').trim())
        .filter(Boolean)
    ),
  })
}

function createCoreNodeHint({
  classType,
  docsUrl = '',
  notes = '',
  displayName = 'ComfyUI core',
  installRecommendation = 'update-comfyui',
  fallbackRepoUrl = '',
}) {
  return Object.freeze({
    classType,
    kind: 'core',
    displayName,
    docsUrl,
    notes,
    installRecommendation,
    fallbackRepoUrl,
  })
}

function createManualNodeHint({
  classType,
  displayName = 'Manual setup required',
  docsUrl = COMFY_REGISTRY_URL,
  notes = '',
  searchTerm = '',
}) {
  return Object.freeze({
    classType,
    kind: 'manual',
    displayName,
    docsUrl,
    notes,
    searchTerm: String(searchTerm || classType || '').trim(),
  })
}

export const CURATED_NODE_PACKS = Object.freeze([
  createAutoNodePack({
    id: 'tk-toolkit',
    displayName: 'TK Toolkit',
    repoUrl: 'https://github.com/Ararararararaki/comfyui-anima-toolkit',
    installDirName: 'ComfyUI-Anima-Batch-LoRA',
    docsUrl: 'https://github.com/Ararararararaki/comfyui-anima-toolkit',
    requirementsStrategy: 'requirements-txt',
    notes: 'Optional MIT-licensed ComfyUI toolbox for visual LoRA management, Civitai metadata and downloads, prompt cards, Danbooru search, output browsing, and batch utilities. Models, previews, and remote service content keep their own licenses and terms.',
    classTypes: ['TK Batch LoRA Loader'],
  }),
  createAutoNodePack({
    id: 'res4lyf',
    displayName: 'RES4LYF',
    repoUrl: 'https://github.com/ClownsharkBatwing/RES4LYF',
    installDirName: 'RES4LYF',
    docsUrl: 'https://github.com/ClownsharkBatwing/RES4LYF/wiki',
    requirementsStrategy: 'requirements-txt',
    notes: 'Approved CANVAS exception for advanced sampling. Provides the source workflow\'s Clownshar sampler and RES exponential/res_2s behavior.',
    classTypes: ['ClownsharKSampler_Beta'],
  }),
  createAutoNodePack({
    id: 'comfyui-vdn-h3', displayName: 'ComfyUI-VDN-H3',
    repoUrl: 'https://github.com/Saganaki22/ComfyUI-VDN-H3', installDirName: 'ComfyUI-VDN-H3',
    requirementsStrategy: 'none', classTypes: ['ApplyVDNH3', 'ApplyVDNH3Advanced'],
    notes: 'VDN hybrid attention for the plain MiniMax H3 base. Includes its own 8-step adapter; do not stack community Turbo or Scheduled SOL attention. Standard grouped mode needs no new Python dependencies.',
  }),
  createAutoNodePack({
    id: 'comfyui-gguf',
    displayName: 'ComfyUI-GGUF',
    repoUrl: 'https://github.com/city96/ComfyUI-GGUF',
    installDirName: 'ComfyUI-GGUF',
    docsUrl: 'https://github.com/city96/ComfyUI-GGUF',
    requirementsStrategy: 'requirements-txt',
    notes: 'Loads supported diffusion models and text encoders in GGUF format.',
    classTypes: ['UnetLoaderGGUF', 'CLIPLoaderGGUF'],
  }),
  createAutoNodePack({
    id: 'comfyui-gguf-qwen3vl-te',
    displayName: 'ComfyUI-GGUF Qwen3-VL Text Encoder Patch',
    repoUrl: 'https://github.com/pottokao-dotcom/ComfyUI-GGUF-Qwen3VL-TE',
    installDirName: 'ComfyUI-GGUF-Qwen3VL-TE',
    docsUrl: 'https://github.com/pottokao-dotcom/ComfyUI-GGUF-Qwen3VL-TE',
    requirementsStrategy: 'none',
    notes: 'Temporary Apache-2.0 add-on required for Qwen Image 2.1 Qwen3-VL GGUF text encoders. It adds no node class; Lumeweft verifies its custom_nodes directory explicitly.',
    classTypes: [],
  }),
  createAutoNodePack({
    id: 'comfyui-h3-multishot',
    displayName: 'ComfyUI-H3-Multishot',
    repoUrl: 'https://github.com/jlucasmcrell/ComfyUI-H3-Multishot',
    installDirName: 'ComfyUI-H3-Multishot',
    docsUrl: 'https://github.com/jlucasmcrell/ComfyUI-H3-Multishot',
    requirementsStrategy: 'requirements-txt',
    notes: 'Provides MiniMax H3 GGUF-aware model/encoder loaders and the in-memory architecture compatibility patch.',
    classTypes: ['H3ModelLoaderAny', 'H3ClipLoaderAny'],
  }),
  createAutoNodePack({
    id: 'minimax-h3-promptor',
    displayName: 'ComfyUI-MiniMax-H3-Promptor',
    repoUrl: 'https://github.com/1038lab/ComfyUI-MiniMax-H3-Promptor',
    installDirName: 'ComfyUI-MiniMax-H3-Promptor',
    docsUrl: 'https://github.com/1038lab/ComfyUI-MiniMax-H3-Promptor',
    requirementsStrategy: 'requirements-txt',
    notes: 'Analyzes image and video references and generates structured MiniMax H3 prompts for CANVAS.',
    classTypes: ['H3_Vision', 'H3_Promptor'],
  }),
  createAutoNodePack({
    id: 'comfy-irodori-tts',
    displayName: 'comfy-Irodori-TTS',
    repoUrl: 'https://github.com/jupo-ai/comfy-Irodori-TTS',
    installDirName: 'comfy-Irodori-TTS',
    docsUrl: 'https://github.com/jupo-ai/comfy-Irodori-TTS',
    requirementsStrategy: 'requirements-txt',
    notes: 'Provides the local Irodori-TTS nodes used by Short Film Creation.',
    classTypes: [
      'jupo.IrodoriTTS.ModelLoader',
      'jupo.IrodoriTTS.Sampler',
      'jupo.IrodoriTTS.ReferenceAudio',
      'jupo.IrodoriTTS.CFGConfig',
      'jupo.IrodoriTTS.VoiceDesignConfig',
    ],
  }),
  createAutoNodePack({
    id: 'comfyui-ltxvideo',
    displayName: 'ComfyUI-LTXVideo',
    repoUrl: 'https://github.com/Lightricks/ComfyUI-LTXVideo',
    installDirName: 'ComfyUI-LTXVideo',
    docsUrl: 'https://github.com/Lightricks/ComfyUI-LTXVideo',
    requirementsStrategy: 'requirements-txt',
    notes: 'Provides native LTX audio-reference conditioning used by the Exact Audio talking-video route.',
    classTypes: ['LTXVSetAudioRefTokens', 'LTXICLoRALoaderModelOnly', 'LTXAddVideoICLoRAGuide'],
  }),
  createAutoNodePack({
    id: 'kjnodes',
    displayName: 'ComfyUI-KJNodes',
    repoUrl: 'https://github.com/kijai/ComfyUI-KJNodes',
    installDirName: 'ComfyUI-KJNodes',
    docsUrl: 'https://github.com/kijai/ComfyUI-KJNodes',
    requirementsStrategy: 'requirements-txt',
    notes: 'Provides image helpers and PathchSageAttentionKJ for H3 acceleration. SageAttention also needs a working sageattention Python package matching the ComfyUI GPU/PyTorch environment; KJNodes requirements do not install it.',
    classTypes: ['ImageResizeKJv2', 'GetImagesFromBatchIndexed', 'PathchSageAttentionKJ', 'DiffusionModelLoaderKJ', 'MiniMaxChunkFeedForward'],
  }),
  createAutoNodePack({
    id: 'h3-sla-attention',
    displayName: 'ComfyUI H3 SLA Attention',
    repoUrl: 'https://github.com/ethanfel/ComfyUI-PlagueKind-Nodes-only-sparse',
    installDirName: 'ComfyUI-PlagueKind-Nodes-only-sparse',
    docsUrl: 'https://github.com/ethanfel/ComfyUI-PlagueKind-Nodes-only-sparse',
    requirementsStrategy: 'none',
    notes: 'Provides the CUDA/Triton H3 SLA block-sparse attention node used by the default MiniMax H3 Fused workflow.',
    classTypes: ['H3SLAAttention'],
  }),
  createAutoNodePack({
    id: 'videohelpersuite',
    displayName: 'ComfyUI-VideoHelperSuite',
    repoUrl: 'https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite',
    installDirName: 'ComfyUI-VideoHelperSuite',
    docsUrl: 'https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite',
    requirementsStrategy: 'requirements-txt',
    notes: 'Used by some advanced/hidden video workflows such as workflow import helpers and caption tooling.',
    classTypes: ['VHS_LoadVideo', 'VHS_LoadVideoPath', 'VHS_LoadAudioUpload'],
  }),
  createAutoNodePack({
    id: 'tts-audio-suite',
    displayName: 'TTS-Audio-Suite',
    repoUrl: 'https://github.com/diodiogod/TTS-Audio-Suite',
    installDirName: 'TTS-Audio-Suite',
    docsUrl: 'https://github.com/diodiogod/TTS-Audio-Suite',
    requirementsStrategy: 'requirements-txt',
    notes: 'Provides Qwen ASR transcription, punctuation/truecase cleanup, and SRT builder nodes used by caption generation and Music Video timed lyrics.',
    classTypes: [
      'UnifiedASRTranscribeNode',
      'Qwen3TTSEngineNode',
      'ASRPunctuationTruecaseNode',
      'TextToSRTBuilderNode',
      'SRTAdvancedOptionsNode',
    ],
  }),
  createAutoNodePack({
    id: 'pysssss-custom-scripts',
    displayName: 'ComfyUI-Custom-Scripts',
    repoUrl: 'https://github.com/pythongosssss/ComfyUI-Custom-Scripts',
    installDirName: 'ComfyUI-Custom-Scripts',
    docsUrl: 'https://github.com/pythongosssss/ComfyUI-Custom-Scripts',
    requirementsStrategy: 'requirements-txt',
    notes: 'Provides Show Text, which the caption workflow uses to expose the generated SRT text back to Velorn.',
    classTypes: ['ShowText|pysssss'],
  }),
  createAutoNodePack({
    id: 'matanyone-kytra',
    displayName: 'ComfyUI_MatAnyone_Kytra',
    repoUrl: 'https://github.com/KytraScript/ComfyUI_MatAnyone_Kytra',
    installDirName: 'ComfyUI_MatAnyone_Kytra',
    docsUrl: 'https://github.com/KytraScript/ComfyUI_MatAnyone_Kytra',
    requirementsStrategy: 'requirements-txt',
    notes: 'Provides MatAnyoneVideoMatting for the bundled mask-generation workflow.',
    classTypes: ['MatAnyoneVideoMatting'],
  }),
])

const AUTO_NODE_PACK_BY_CLASS_TYPE = Object.freeze(
  CURATED_NODE_PACKS.reduce((acc, pack) => {
    for (const classType of pack.classTypes) {
      acc[classType] = pack
    }
    return acc
  }, {})
)

export const CORE_NODE_HINTS = Object.freeze({
  ImageScale: createCoreNodeHint({ classType: 'ImageScale', notes: 'ComfyUI core image resizing.' }),
  EmptyImage: createCoreNodeHint({ classType: 'EmptyImage', notes: 'ComfyUI core solid-color image batches.' }),
  ImageBatch: createCoreNodeHint({ classType: 'ImageBatch', notes: 'ComfyUI core image batch concatenation.' }),
  EmptyAudio: createCoreNodeHint({ classType: 'EmptyAudio', notes: 'Update ComfyUI for the AInVFX Fluid silent audio input.' }),
  VAEEncodeAudio: createCoreNodeHint({ classType: 'VAEEncodeAudio', notes: 'Requires current ComfyUI with LTX 2.5 audio VAE support.' }),
  MiniMaxH3ReferenceToVideo: createCoreNodeHint({
    classType: 'MiniMaxH3ReferenceToVideo',
    docsUrl: 'https://huggingface.co/PoopMan333/H3_Character_Sheet_Generator',
    notes: 'MiniMax H3 reference-to-video support ships with current ComfyUI builds. Update ComfyUI if this node is missing.',
  }),
  ImageFromBatch: createCoreNodeHint({
    classType: 'ImageFromBatch',
    docsUrl: `${COMFY_REGISTRY_URL}`,
    notes: 'Core batch-image extraction node. Update ComfyUI if it is missing.',
  }),
  ImageStitch: createCoreNodeHint({
    classType: 'ImageStitch',
    docsUrl: `${COMFY_REGISTRY_URL}`,
    notes: 'Core image-stitching node used to assemble the final character sheet. Update ComfyUI if it is missing.',
  }),
  MiniMaxH3ImageToVideo: createCoreNodeHint({
    classType: 'MiniMaxH3ImageToVideo',
    docsUrl: 'https://docs.comfy.org/built-in-nodes/MiniMaxH3ImageToVideo',
    notes: 'MiniMax H3 support requires ComfyUI 0.30.0 or newer. Update ComfyUI if this node is missing.',
  }),
  MiniMaxH3SigmaShift: createCoreNodeHint({
    classType: 'MiniMaxH3SigmaShift',
    docsUrl: 'https://docs.comfy.org/built-in-nodes/MiniMaxH3SigmaShift',
    notes: 'MiniMax H3 audio/video sigma scheduling ships with current ComfyUI builds.',
  }),
  BatchImagesNode: createCoreNodeHint({
    classType: 'BatchImagesNode',
    docsUrl: `${COMFY_REGISTRY_URL}`,
    notes: 'This ships with modern ComfyUI builds. If it is missing, update ComfyUI first.',
  }),
  BasicGuider: createCoreNodeHint({
    classType: 'BasicGuider',
    docsUrl: `${COMFY_REGISTRY_URL}`,
    notes: 'Core guider node used by modern sampler graphs. Missing this usually means ComfyUI is outdated.',
  }),
  CFGGuider: createCoreNodeHint({
    classType: 'CFGGuider',
    docsUrl: `${COMFY_REGISTRY_URL}`,
    notes: 'Core guider node used by advanced sampler graphs. Missing this usually means ComfyUI is outdated.',
  }),
  CheckpointLoaderSimple: createCoreNodeHint({
    classType: 'CheckpointLoaderSimple',
    docsUrl: `${COMFY_REGISTRY_URL}`,
    notes: 'Core checkpoint loader. Missing this usually means the ComfyUI install is incomplete or very outdated.',
  }),
  CLIPLoader: createCoreNodeHint({
    classType: 'CLIPLoader',
    docsUrl: `${COMFY_REGISTRY_URL}`,
    notes: 'Core text-encoder loader. Missing this usually means the ComfyUI install is incomplete or very outdated.',
  }),
  CLIPTextEncode: createCoreNodeHint({
    classType: 'CLIPTextEncode',
    docsUrl: `${COMFY_REGISTRY_URL}`,
    notes: 'Core text encoding node. Missing this usually means the ComfyUI install is incomplete or very outdated.',
  }),
  ConditioningZeroOut: createCoreNodeHint({
    classType: 'ConditioningZeroOut',
    docsUrl: `${COMFY_REGISTRY_URL}`,
    notes: 'Core conditioning utility. Missing this usually means ComfyUI is outdated.',
  }),
  CreateVideo: createCoreNodeHint({
    classType: 'CreateVideo',
    docsUrl: 'https://docs.comfy.org/built-in-nodes/CreateVideo',
    notes: 'CreateVideo is part of newer ComfyUI builds.',
  }),
  EmptyFlux2LatentImage: createCoreNodeHint({
    classType: 'EmptyFlux2LatentImage',
    docsUrl: `${COMFY_REGISTRY_URL}`,
    notes: 'Flux 2 latent support ships with newer ComfyUI builds.',
  }),
  EmptyHunyuanLatentVideo: createCoreNodeHint({
    classType: 'EmptyHunyuanLatentVideo',
    docsUrl: `${COMFY_REGISTRY_URL}`,
    notes: 'Core latent-video node used by WAN text-to-video graphs. Update ComfyUI if this is missing.',
  }),
  'EmptyAceStep1.5LatentAudio': createCoreNodeHint({
    classType: 'EmptyAceStep1.5LatentAudio',
    docsUrl: 'https://docs.comfy.org/tutorials/audio/ace-step/ace-step-v1',
    notes: 'Ace-Step nodes are bundled into newer ComfyUI builds. Update ComfyUI if this is missing.',
  }),
  EmptyLTXVLatentVideo: createCoreNodeHint({
    classType: 'EmptyLTXVLatentVideo',
    docsUrl: 'https://docs.comfy.org/built-in-nodes/EmptyLTXVLatentVideo',
    notes: 'LTX 2.3 workflow support is built into newer ComfyUI builds.',
  }),
  EmptySD3LatentImage: createCoreNodeHint({
    classType: 'EmptySD3LatentImage',
    docsUrl: `${COMFY_REGISTRY_URL}`,
    notes: 'Core SD3-style latent node used by Flux/LongCat graphs. Update ComfyUI if this is missing.',
  }),
  Flux2Scheduler: createCoreNodeHint({
    classType: 'Flux2Scheduler',
    docsUrl: `${COMFY_REGISTRY_URL}`,
    notes: 'Flux 2 scheduler support ships with newer ComfyUI builds.',
  }),
  FluxGuidance: createCoreNodeHint({
    classType: 'FluxGuidance',
    docsUrl: `${COMFY_REGISTRY_URL}`,
    notes: 'Flux guidance support ships with newer ComfyUI builds.',
  }),
  FluxKontextImageScale: createCoreNodeHint({
    classType: 'FluxKontextImageScale',
    docsUrl: `${COMFY_REGISTRY_URL}`,
    notes: 'Qwen/Flux edit support ships with current ComfyUI releases.',
  }),
  ImageScaleToTotalPixels: createCoreNodeHint({
    classType: 'ImageScaleToTotalPixels',
    docsUrl: `${COMFY_REGISTRY_URL}`,
    notes: 'Core image sizing utility. Update ComfyUI if this is missing.',
  }),
  ImageCompositeMasked: createCoreNodeHint({
    classType: 'ImageCompositeMasked',
    docsUrl: `${COMFY_REGISTRY_URL}`,
    notes: 'Core masked image compositing node. Update ComfyUI if this is missing.',
  }),
  ImageToMask: createCoreNodeHint({
    classType: 'ImageToMask',
    docsUrl: `${COMFY_REGISTRY_URL}`,
    notes: 'Core mask conversion node. Missing this usually means the ComfyUI install is incomplete or very outdated.',
  }),
  KSampler: createCoreNodeHint({
    classType: 'KSampler',
    docsUrl: `${COMFY_REGISTRY_URL}`,
    notes: 'Core sampler node. Missing this usually means the ComfyUI install is incomplete or very outdated.',
  }),
  KSamplerAdvanced: createCoreNodeHint({
    classType: 'KSamplerAdvanced',
    docsUrl: `${COMFY_REGISTRY_URL}`,
    notes: 'Core advanced sampler node. Missing this usually means the ComfyUI install is incomplete or very outdated.',
  }),
  KSamplerSelect: createCoreNodeHint({
    classType: 'KSamplerSelect',
    docsUrl: `${COMFY_REGISTRY_URL}`,
    notes: 'Core sampler selection node used by advanced sampler graphs. Update ComfyUI if this is missing.',
  }),
  LatentUpscaleModelLoader: createCoreNodeHint({
    classType: 'LatentUpscaleModelLoader',
    docsUrl: 'https://docs.comfy.org/built-in-nodes/LatentUpscaleModelLoader',
    notes: 'This loader is built into ComfyUI. Missing it usually means the install is outdated.',
  }),
  LoadAudio: createCoreNodeHint({
    classType: 'LoadAudio',
    docsUrl: `${COMFY_REGISTRY_URL}`,
    notes: 'Core audio input node. Update ComfyUI if this is missing.',
  }),
  LoadImage: createCoreNodeHint({
    classType: 'LoadImage',
    docsUrl: `${COMFY_REGISTRY_URL}`,
    notes: 'Core image input node. Missing this usually means the ComfyUI install is incomplete or very outdated.',
  }),
  LoadVideo: createCoreNodeHint({
    classType: 'LoadVideo',
    docsUrl: `${COMFY_REGISTRY_URL}`,
    notes: 'Core video input node. Update ComfyUI if this is missing.',
  }),
  LoraLoaderModelOnly: createCoreNodeHint({
    classType: 'LoraLoaderModelOnly',
    docsUrl: `${COMFY_REGISTRY_URL}`,
    notes: 'Core LoRA loader. Missing this usually means the ComfyUI install is incomplete or very outdated.',
  }),
  MaskToImage: createCoreNodeHint({
    classType: 'MaskToImage',
    docsUrl: `${COMFY_REGISTRY_URL}`,
    notes: 'Core mask conversion node. Missing this usually means the ComfyUI install is incomplete or very outdated.',
  }),
  LTXAVTextEncoderLoader: createCoreNodeHint({
    classType: 'LTXAVTextEncoderLoader',
    docsUrl: 'https://docs.comfy.org/tutorials/video/ltx/ltx-2-3',
    notes: 'Update ComfyUI to a build with LTX 2.3 support. If that still does not expose the node, install or update ComfyUI-LTXVideo manually.',
    fallbackRepoUrl: 'https://github.com/Lightricks/ComfyUI-LTXVideo',
  }),
  LTXVAudioVAEDecode: createCoreNodeHint({
    classType: 'LTXVAudioVAEDecode',
    docsUrl: 'https://docs.comfy.org/tutorials/video/ltx/ltx-2-3',
    notes: 'Update ComfyUI to a build with LTX 2.3 support. If that still does not expose the node, install or update ComfyUI-LTXVideo manually.',
    fallbackRepoUrl: 'https://github.com/Lightricks/ComfyUI-LTXVideo',
  }),
  LTXVAudioVAELoader: createCoreNodeHint({
    classType: 'LTXVAudioVAELoader',
    docsUrl: 'https://docs.comfy.org/built-in-nodes/LTXVAudioVAELoader',
    notes: 'Update ComfyUI to a build with LTX 2.3 support. If that still does not expose the node, install or update ComfyUI-LTXVideo manually.',
    fallbackRepoUrl: 'https://github.com/Lightricks/ComfyUI-LTXVideo',
  }),
  LTXVConcatAVLatent: createCoreNodeHint({
    classType: 'LTXVConcatAVLatent',
    docsUrl: 'https://docs.comfy.org/tutorials/video/ltx/ltx-2-3',
    notes: 'LTX workflow nodes are bundled into newer ComfyUI builds.',
    fallbackRepoUrl: 'https://github.com/Lightricks/ComfyUI-LTXVideo',
  }),
  LTXVConditioning: createCoreNodeHint({
    classType: 'LTXVConditioning',
    docsUrl: 'https://docs.comfy.org/tutorials/video/ltx/ltx-2-3',
    notes: 'LTX workflow nodes are bundled into newer ComfyUI builds.',
    fallbackRepoUrl: 'https://github.com/Lightricks/ComfyUI-LTXVideo',
  }),
  LTXVCropGuides: createCoreNodeHint({
    classType: 'LTXVCropGuides',
    docsUrl: 'https://docs.comfy.org/tutorials/video/ltx/ltx-2-3',
    notes: 'LTX workflow nodes are bundled into newer ComfyUI builds.',
    fallbackRepoUrl: 'https://github.com/Lightricks/ComfyUI-LTXVideo',
  }),
  LTXVEmptyLatentAudio: createCoreNodeHint({
    classType: 'LTXVEmptyLatentAudio',
    docsUrl: 'https://docs.comfy.org/tutorials/video/ltx/ltx-2-3',
    notes: 'LTX workflow nodes are bundled into newer ComfyUI builds.',
    fallbackRepoUrl: 'https://github.com/Lightricks/ComfyUI-LTXVideo',
  }),
  LTXVImgToVideoInplace: createCoreNodeHint({
    classType: 'LTXVImgToVideoInplace',
    docsUrl: 'https://docs.comfy.org/tutorials/video/ltx/ltx-2-3',
    notes: 'LTX workflow nodes are bundled into newer ComfyUI builds.',
    fallbackRepoUrl: 'https://github.com/Lightricks/ComfyUI-LTXVideo',
  }),
  LTXVLatentUpsampler: createCoreNodeHint({
    classType: 'LTXVLatentUpsampler',
    docsUrl: 'https://docs.comfy.org/tutorials/video/ltx/ltx-2-3',
    notes: 'LTX workflow nodes are bundled into newer ComfyUI builds.',
    fallbackRepoUrl: 'https://github.com/Lightricks/ComfyUI-LTXVideo',
  }),
  LTXVPreprocess: createCoreNodeHint({
    classType: 'LTXVPreprocess',
    docsUrl: 'https://docs.comfy.org/tutorials/video/ltx/ltx-2-3',
    notes: 'LTX workflow nodes are bundled into newer ComfyUI builds.',
    fallbackRepoUrl: 'https://github.com/Lightricks/ComfyUI-LTXVideo',
  }),
  LTXVSeparateAVLatent: createCoreNodeHint({
    classType: 'LTXVSeparateAVLatent',
    docsUrl: 'https://docs.comfy.org/tutorials/video/ltx/ltx-2-3',
    notes: 'LTX workflow nodes are bundled into newer ComfyUI builds.',
    fallbackRepoUrl: 'https://github.com/Lightricks/ComfyUI-LTXVideo',
  }),
  ModelSamplingAuraFlow: createCoreNodeHint({
    classType: 'ModelSamplingAuraFlow',
    docsUrl: 'https://docs.comfy.org/built-in-nodes/ModelSamplingAuraFlow',
    notes: 'This sampler ships with newer ComfyUI builds.',
  }),
  ManualSigmas: createCoreNodeHint({
    classType: 'ManualSigmas',
    docsUrl: `${COMFY_REGISTRY_URL}`,
    notes: 'Core sigma schedule node used by advanced sampler graphs. Update ComfyUI if this is missing.',
  }),
  ModelSamplingSD3: createCoreNodeHint({
    classType: 'ModelSamplingSD3',
    docsUrl: `${COMFY_REGISTRY_URL}`,
    notes: 'Core SD3-style model sampling node used by WAN text-to-video. Update ComfyUI if this is missing.',
  }),
  RandomNoise: createCoreNodeHint({
    classType: 'RandomNoise',
    docsUrl: `${COMFY_REGISTRY_URL}`,
    notes: 'Core sampler noise node. Missing this usually means ComfyUI is outdated.',
  }),
  ResizeImageMaskNode: createCoreNodeHint({
    classType: 'ResizeImageMaskNode',
    docsUrl: `${COMFY_REGISTRY_URL}`,
    notes: 'Part of current ComfyUI core image utilities.',
  }),
  ResizeImagesByLongerEdge: createCoreNodeHint({
    classType: 'ResizeImagesByLongerEdge',
    docsUrl: 'https://docs.comfy.org/built-in-nodes/ResizeImagesByLongerEdge',
    notes: 'Part of current ComfyUI core image utilities.',
  }),
  SaveAudioMP3: createCoreNodeHint({
    classType: 'SaveAudioMP3',
    docsUrl: 'https://docs.comfy.org/tutorials/audio/ace-step/ace-step-v1',
    notes: 'Ace-Step audio save nodes are included in newer ComfyUI builds.',
  }),
  SaveAudioAdvanced: createCoreNodeHint({
    classType: 'SaveAudioAdvanced',
    docsUrl: 'https://docs.comfy.org/tutorials/audio/ace-step/ace-step-v1',
    notes: 'Advanced audio output is included in newer ComfyUI builds. Update ComfyUI if this node is missing.',
  }),
  SaveImage: createCoreNodeHint({
    classType: 'SaveImage',
    docsUrl: `${COMFY_REGISTRY_URL}`,
    notes: 'Core image output node. Missing this usually means the ComfyUI install is incomplete or very outdated.',
  }),
  SaveVideo: createCoreNodeHint({
    classType: 'SaveVideo',
    docsUrl: 'https://docs.comfy.org/built-in-nodes/CreateVideo',
    notes: 'Core video output support ships with newer ComfyUI builds.',
  }),
  SamplerCustomAdvanced: createCoreNodeHint({
    classType: 'SamplerCustomAdvanced',
    docsUrl: `${COMFY_REGISTRY_URL}`,
    notes: 'Core advanced sampler node. Missing this usually means ComfyUI is outdated.',
  }),
  SetLatentNoiseMask: createCoreNodeHint({
    classType: 'SetLatentNoiseMask',
    docsUrl: `${COMFY_REGISTRY_URL}`,
    notes: 'Core latent-mask utility. Missing this usually means ComfyUI is outdated.',
  }),
  'TextEncodeAceStepAudio1.5': createCoreNodeHint({
    classType: 'TextEncodeAceStepAudio1.5',
    docsUrl: 'https://docs.comfy.org/tutorials/audio/ace-step/ace-step-v1',
    notes: 'Update ComfyUI to a build with Ace-Step 1.5 support if this node is missing.',
  }),
  TextEncodeQwenImageEdit: createCoreNodeHint({
    classType: 'TextEncodeQwenImageEdit',
    docsUrl: `${COMFY_REGISTRY_URL}`,
    notes: 'Native Qwen/LongCat image edit support ships with newer ComfyUI builds.',
  }),
  TextEncodeQwenImageEditPlus: createCoreNodeHint({
    classType: 'TextEncodeQwenImageEditPlus',
    docsUrl: 'https://docs.comfy.org/built-in-nodes/TextEncodeQwenImageEditPlus',
    notes: 'Native Qwen image edit support ships with newer ComfyUI builds.',
  }),
  TextEncodeQwenImage21: createCoreNodeHint({
    classType: 'TextEncodeQwenImage21',
    docsUrl: 'https://blog.comfy.org/p/qwen-image-21-in-comfyui-open-weight',
    notes: 'Qwen Image 2.1 support requires ComfyUI 0.36.0 or newer. Update ComfyUI if this node is missing.',
  }),
  UNETLoader: createCoreNodeHint({
    classType: 'UNETLoader',
    docsUrl: `${COMFY_REGISTRY_URL}`,
    notes: 'Core diffusion model loader. Missing this usually means the ComfyUI install is incomplete or very outdated.',
  }),
  VAEDecodeAudio: createCoreNodeHint({
    classType: 'VAEDecodeAudio',
    docsUrl: 'https://docs.comfy.org/tutorials/audio/ace-step/ace-step-v1',
    notes: 'Ace-Step audio decode support ships with newer ComfyUI builds.',
  }),
  VAEDecodeTiled: createCoreNodeHint({
    classType: 'VAEDecodeTiled',
    docsUrl: 'https://docs.comfy.org/built-in-nodes/VAEDecodeTiled',
    notes: 'Tiled VAE decode is part of current ComfyUI core.',
  }),
  VAELoader: createCoreNodeHint({
    classType: 'VAELoader',
    docsUrl: `${COMFY_REGISTRY_URL}`,
    notes: 'Core VAE loader. Missing this usually means the ComfyUI install is incomplete or very outdated.',
  }),
  WanImageToVideo: createCoreNodeHint({
    classType: 'WanImageToVideo',
    docsUrl: 'https://docs.comfy.org/tutorials/video/wan/wan2_2',
    notes: 'Update ComfyUI first. If WanImageToVideo is still missing afterwards, install a maintained Wan wrapper such as ComfyUI-WanVideoWrapper manually.',
    fallbackRepoUrl: 'https://github.com/kijai/ComfyUI-WanVideoWrapper',
  }),
})

export const MANUAL_NODE_HINTS = Object.freeze({
  ByteDanceSeedreamNode: createManualNodeHint({
    classType: 'ByteDanceSeedreamNode',
    displayName: 'Partner node via Comfy Registry',
    notes: 'This cloud partner node is not mapped to a stable unattended install recipe yet. Use the registry or ComfyUI Manager.',
  }),
  ByteDance2FirstLastFrameNode: createManualNodeHint({
    classType: 'ByteDance2FirstLastFrameNode',
    displayName: 'Partner node via Comfy Registry',
    notes: 'This Seedance 2.0 cloud partner node is not mapped to a stable unattended install recipe yet. Use the registry or ComfyUI Manager.',
  }),
  ByteDance2ReferenceNode: createManualNodeHint({
    classType: 'ByteDance2ReferenceNode',
    displayName: 'Partner node via Comfy Registry',
    notes: 'This Seedance 2.0 cloud partner node is not mapped to a stable unattended install recipe yet. Use the registry or ComfyUI Manager.',
  }),
  ByteDance2TextToVideoNode: createManualNodeHint({
    classType: 'ByteDance2TextToVideoNode',
    displayName: 'Partner node via Comfy Registry',
    notes: 'This Seedance 2.0 cloud partner node is not mapped to a stable unattended install recipe yet. Use the registry or ComfyUI Manager.',
  }),
  CFGNorm: createManualNodeHint({
    classType: 'CFGNorm',
    displayName: 'LongCat helper node',
    notes: 'Install the LongCat/Flux helper nodes through the Comfy Registry or ComfyUI Manager if this is missing.',
    searchTerm: 'CFGNorm LongCat ComfyUI',
  }),
  ComfyMathExpression: createManualNodeHint({
    classType: 'ComfyMathExpression',
    displayName: 'ComfyUI helper node',
    notes: 'Install the helper/custom-node pack that provides ComfyMathExpression through the Comfy Registry or ComfyUI Manager.',
    searchTerm: 'ComfyMathExpression',
  }),
  ComfySwitchNode: createManualNodeHint({
    classType: 'ComfySwitchNode',
    displayName: 'ComfyUI helper node',
    notes: 'Install the helper/custom-node pack that provides ComfySwitchNode through the Comfy Registry or ComfyUI Manager.',
    searchTerm: 'ComfySwitchNode',
  }),
  FluxKontextMultiReferenceLatentMethod: createManualNodeHint({
    classType: 'FluxKontextMultiReferenceLatentMethod',
    displayName: 'Flux/LongCat helper node',
    notes: 'Install the Flux Kontext/LongCat helper nodes through the Comfy Registry or ComfyUI Manager if this is missing.',
    searchTerm: 'FluxKontextMultiReferenceLatentMethod',
  }),
  FrameInterpolate: createManualNodeHint({
    classType: 'FrameInterpolate',
    displayName: 'Frame interpolation nodes',
    docsUrl: 'https://github.com/Fannovel16/ComfyUI-Frame-Interpolation',
    notes: 'Install ComfyUI-Frame-Interpolation or an equivalent frame interpolation node pack.',
    searchTerm: 'ComfyUI-Frame-Interpolation',
  }),
  FrameInterpolationModelLoader: createManualNodeHint({
    classType: 'FrameInterpolationModelLoader',
    displayName: 'Frame interpolation nodes',
    docsUrl: 'https://github.com/Fannovel16/ComfyUI-Frame-Interpolation',
    notes: 'Install ComfyUI-Frame-Interpolation or an equivalent frame interpolation node pack.',
    searchTerm: 'ComfyUI-Frame-Interpolation',
  }),
  GeminiNanoBanana2: createManualNodeHint({
    classType: 'GeminiNanoBanana2',
    displayName: 'Partner node via Comfy Registry',
    notes: 'This cloud partner node is not mapped to a stable unattended install recipe yet. Use the registry or ComfyUI Manager.',
  }),
  GeminiNode: createManualNodeHint({
    classType: 'GeminiNode',
    displayName: 'Partner node via Comfy Registry',
    notes: 'This cloud partner node is not mapped to a stable unattended install recipe yet. Use the registry or ComfyUI Manager.',
  }),
  GetVideoComponents: createManualNodeHint({
    classType: 'GetVideoComponents',
    displayName: 'Video helper node',
    notes: 'Install the video helper/custom-node pack that provides GetVideoComponents through the Comfy Registry or ComfyUI Manager.',
    searchTerm: 'GetVideoComponents',
  }),
  GrokImageNode: createManualNodeHint({
    classType: 'GrokImageNode',
    displayName: 'Partner node via Comfy Registry',
    notes: 'This cloud partner node is not mapped to a stable unattended install recipe yet. Use the registry or ComfyUI Manager.',
  }),
  GrokVideoNode: createManualNodeHint({
    classType: 'GrokVideoNode',
    displayName: 'Partner node via Comfy Registry',
    notes: 'This cloud partner node is not mapped to a stable unattended install recipe yet. Use the registry or ComfyUI Manager.',
  }),
  KlingOmniProImageToVideoNode: createManualNodeHint({
    classType: 'KlingOmniProImageToVideoNode',
    displayName: 'Partner node via Comfy Registry',
    notes: 'This cloud partner node is not mapped to a stable unattended install recipe yet. Use the registry or ComfyUI Manager.',
  }),
  OpenAIGPTImage1: createManualNodeHint({
    classType: 'OpenAIGPTImage1',
    displayName: 'Partner node via Comfy Registry',
    notes: 'This OpenAI cloud partner node is not mapped to a stable unattended install recipe yet. Use the registry or ComfyUI Manager.',
  }),
  LoadSAM3Model: createManualNodeHint({
    classType: 'LoadSAM3Model',
    displayName: 'ComfyUI-SAM3',
    docsUrl: 'https://github.com/PozzettiAndrea/ComfyUI-SAM3',
    notes: 'Install via ComfyUI Manager or clone ComfyUI-SAM3 and run `python install.py`. This pack uses a comfy-env installer instead of a plain requirements.txt flow.',
    searchTerm: 'ComfyUI-SAM3',
  }),
  SAM3Propagate: createManualNodeHint({
    classType: 'SAM3Propagate',
    displayName: 'ComfyUI-SAM3',
    docsUrl: 'https://github.com/PozzettiAndrea/ComfyUI-SAM3',
    notes: 'Install via ComfyUI Manager or clone ComfyUI-SAM3 and run `python install.py`. This pack uses a comfy-env installer instead of a plain requirements.txt flow.',
    searchTerm: 'ComfyUI-SAM3',
  }),
  SAM3VideoOutput: createManualNodeHint({
    classType: 'SAM3VideoOutput',
    displayName: 'ComfyUI-SAM3',
    docsUrl: 'https://github.com/PozzettiAndrea/ComfyUI-SAM3',
    notes: 'Install via ComfyUI Manager or clone ComfyUI-SAM3 and run `python install.py`. This pack uses a comfy-env installer instead of a plain requirements.txt flow.',
    searchTerm: 'ComfyUI-SAM3',
  }),
  SAM3VideoSegmentation: createManualNodeHint({
    classType: 'SAM3VideoSegmentation',
    displayName: 'ComfyUI-SAM3',
    docsUrl: 'https://github.com/PozzettiAndrea/ComfyUI-SAM3',
    notes: 'Install via ComfyUI Manager or clone ComfyUI-SAM3 and run `python install.py`. This pack uses a comfy-env installer instead of a plain requirements.txt flow.',
    searchTerm: 'ComfyUI-SAM3',
  }),
  PreviewAny: createManualNodeHint({
    classType: 'PreviewAny',
    displayName: 'Preview helper node',
    notes: 'Install the preview/helper custom-node pack that provides PreviewAny through the Comfy Registry or ComfyUI Manager.',
    searchTerm: 'PreviewAny',
  }),
  ResolutionSelector: createManualNodeHint({
    classType: 'ResolutionSelector',
    displayName: 'Resolution helper node',
    notes: 'Install the helper/custom-node pack that provides ResolutionSelector through the Comfy Registry or ComfyUI Manager.',
    searchTerm: 'ResolutionSelector',
  }),
  StringReplace: createManualNodeHint({
    classType: 'StringReplace',
    displayName: 'Text helper node',
    notes: 'Install the text/helper custom-node pack that provides StringReplace through the Comfy Registry or ComfyUI Manager.',
    searchTerm: 'StringReplace',
  }),
  SoniloVideoToMusic: createManualNodeHint({
    classType: 'SoniloVideoToMusic',
    displayName: 'Partner node via Comfy Registry',
    notes: 'This Sonilo cloud partner node is not mapped to a stable unattended install recipe yet. Use the registry or ComfyUI Manager.',
  }),
  TextGenerate: createManualNodeHint({
    classType: 'TextGenerate',
    displayName: 'Text generation helper node',
    notes: 'Install the text-generation helper nodes used by the Ernie prompt enhancer through the Comfy Registry or ComfyUI Manager.',
    searchTerm: 'TextGenerate ComfyUI',
  }),
  TopazVideoEnhance: createManualNodeHint({
    classType: 'TopazVideoEnhance',
    displayName: 'Partner node via Comfy Registry',
    notes: 'This cloud partner node is not mapped to a stable unattended install recipe yet. Use the registry or ComfyUI Manager.',
  }),
  Vidu2ImageToVideoNode: createManualNodeHint({
    classType: 'Vidu2ImageToVideoNode',
    displayName: 'Partner node via Comfy Registry',
    notes: 'This cloud partner node is not mapped to a stable unattended install recipe yet. Use the registry or ComfyUI Manager.',
  }),
})

export const MODEL_INSTALL_RECIPES = Object.freeze({
  [modelKey('diffusion_models', 'qwen_image_2.1_int8_convrot.safetensors')]: createModelRecipe({
    filename: 'qwen_image_2.1_int8_convrot.safetensors', targetSubdir: 'diffusion_models', displayName: 'Qwen Image 2.1 INT8 ConvRot',
    downloadUrl: hfResolve('Comfy-Org/Qwen-Image-2.1', 'diffusion_models/qwen_image_2.1_int8_convrot.safetensors'),
    sourceUrl: hfBlob('Comfy-Org/Qwen-Image-2.1', 'diffusion_models/qwen_image_2.1_int8_convrot.safetensors'),
    licenseUrl: 'https://huggingface.co/Qwen/Qwen-Image-2.1/blob/main/LICENSE',
    sizeBytes: 7256783064, sha256: 'cb74113cb03faecd79611b01fd7fd642f0aa60d6f0b95086abee214d75eaa57d',
    notes: 'Official ComfyUI-packaged Qwen Image 2.1 diffusion model. Qwen Research License applies.',
  }),
  [modelKey('text_encoders', 'qwen3vl_8b_heretic-Q4_K_M.gguf')]: createModelRecipe({
    filename: 'qwen3vl_8b_heretic-Q4_K_M.gguf', targetSubdir: 'text_encoders', displayName: 'Qwen Image 2.1 Heretic text encoder Q4_K_M',
    downloadUrl: hfResolve('pottokao/Qwen-Image-2.1-Text-Encoder-Heretic-GGUF', 'qwen3vl_8b_heretic-Q4_K_M.gguf'),
    sourceUrl: hfBlob('pottokao/Qwen-Image-2.1-Text-Encoder-Heretic-GGUF', 'qwen3vl_8b_heretic-Q4_K_M.gguf'),
    licenseUrl: 'https://huggingface.co/pottokao/Qwen-Image-2.1-Text-Encoder-Heretic-GGUF/blob/main/LICENSE',
    sizeBytes: 5027785376, sha256: '1338274ac7a6344f262a16c7a52d1bd7fe789307d252733b23ea421126e5d343',
    notes: 'Requested refusal-ablated community text encoder. Keep its original filename and the matching mmproj beside it.',
  }),
  [modelKey('text_encoders', 'mmproj-qwen3vl_8b_heretic-f16.gguf')]: createModelRecipe({
    filename: 'mmproj-qwen3vl_8b_heretic-f16.gguf', targetSubdir: 'text_encoders', displayName: 'Qwen Image 2.1 Heretic vision tower F16',
    downloadUrl: hfResolve('pottokao/Qwen-Image-2.1-Text-Encoder-Heretic-GGUF', 'mmproj-qwen3vl_8b_heretic-f16.gguf'),
    sourceUrl: hfBlob('pottokao/Qwen-Image-2.1-Text-Encoder-Heretic-GGUF', 'mmproj-qwen3vl_8b_heretic-f16.gguf'),
    licenseUrl: 'https://huggingface.co/pottokao/Qwen-Image-2.1-Text-Encoder-Heretic-GGUF/blob/main/LICENSE',
    sizeBytes: 1159030464, sha256: '4649839491c8df1ebc9bed2de158ad2a45b53ed1d3b311d92a69056b6764f101',
    notes: 'Required Qwen3-VL vision tower. Do not rename it; the patch matches it to the Heretic GGUF encoder by filename.',
  }),
  [modelKey('vae', 'qwen_image_2.1_vae_bf16.safetensors')]: createModelRecipe({
    filename: 'qwen_image_2.1_vae_bf16.safetensors', targetSubdir: 'vae', displayName: 'Qwen Image 2.1 VAE BF16',
    downloadUrl: hfResolve('Comfy-Org/Qwen-Image-2.1', 'vae/qwen_image_2.1_vae_bf16.safetensors'),
    sourceUrl: hfBlob('Comfy-Org/Qwen-Image-2.1', 'vae/qwen_image_2.1_vae_bf16.safetensors'),
    licenseUrl: 'https://huggingface.co/Qwen/Qwen-Image-2.1/blob/main/LICENSE',
    sizeBytes: 675509688, sha256: 'bb21f7473051e1ac368515dd3f2e15cd44d7a11748ee8823e1ddca3e4876b7c9',
    notes: 'Official Qwen Image 2.1 VAE with native RGBA decoding.',
  }),
  [modelKey('loras', 'NSFW Qwen Lora.safetensors')]: createModelRecipe({
    filename: 'NSFW Qwen Lora.safetensors', targetSubdir: 'loras', displayName: 'NSFW LoRA for Qwen Image 2.1 v1.0',
    downloadUrl: '',
    sourceUrl: 'https://civitai.red/models/2958918/nsfw-lora-or-qwen-image-21?modelVersionId=3351951',
    sizeBytes: 159436456, sha256: 'c29f503f3515877882fd6b10f6849c78a4f2337c09021f4bd4b93d060c311aea',
    notes: 'Civitai model version 3351951. Install through Generate > Community so the saved Civitai API key and consent gate are respected.',
  }),
  ...Object.fromEntries(AINVFX_FLUID_MODELS.map(model => [modelKey(model.targetSubdir, model.filename), createModelRecipe(model)])),
  ...Object.fromEntries(VDN_H3_STAGE_FILES.map(file => [modelKey(file.targetSubdir, file.filename), createModelRecipe({
    ...file, displayName: 'VDN-H3 ' + file.relativePath.replace('stage-dmd-step-250/', ''),
    downloadUrl: hfResolve('OpenVDN/vdn-minimax-h3', file.relativePath),
    sourceUrl: hfBlob('OpenVDN/vdn-minimax-h3', file.relativePath),
    licenseUrl: 'https://huggingface.co/OpenVDN/vdn-minimax-h3/blob/main/LICENSE',
    notes: 'Part of the complete 8-step VDN stage. Keep its exact directory layout.',
  })])),
  [modelKey('diffusion_models', 'minimax_h3_fl2va_int8_convrot.safetensors')]: createModelRecipe({
    filename: 'minimax_h3_fl2va_int8_convrot.safetensors', targetSubdir: 'diffusion_models', displayName: 'MiniMax H3 FL2VA INT8 ConvRot (VDN base)',
    downloadUrl: hfResolve('Comfy-Org/MiniMax-H3', 'diffusion_models/minimax_h3_fl2va_int8_convrot.safetensors'),
    sourceUrl: hfBlob('Comfy-Org/MiniMax-H3', 'diffusion_models/minimax_h3_fl2va_int8_convrot.safetensors'),
    licenseUrl: 'https://huggingface.co/MiniMaxAI/MiniMax-H3/blob/main/LICENSE',
    sizeBytes: 34038892334, sha256: '7ad4c73e6e378b822ffd1629f27f632d3787d95f5e468e3af958f98c58df96a5',
    notes: 'Plain base for VDN; do not substitute the Fast H3 Turbo/Mystic fused model.',
  }),
  [modelKey('diffusion_models', 'minimax_h3_fl2va_pruned_int8_convrot.safetensors')]: createModelRecipe({
    filename: 'minimax_h3_fl2va_pruned_int8_convrot.safetensors', targetSubdir: 'diffusion_models', displayName: 'MiniMax H3 FL2VA Pruned INT8 ConvRot',
    downloadUrl: hfResolve('Comfy-Org/MiniMax-H3', 'diffusion_models/minimax_h3_fl2va_pruned_int8_convrot.safetensors'),
    sourceUrl: hfBlob('Comfy-Org/MiniMax-H3', 'diffusion_models/minimax_h3_fl2va_pruned_int8_convrot.safetensors'),
    licenseUrl: 'https://huggingface.co/MiniMaxAI/MiniMax-H3/blob/main/LICENSE',
    sizeBytes: 20970379616, sha256: 'e889202c41dafb67b10d67b97f0d8541508036a6090af23425a5c2615d03c47a',
    notes: 'Official ComfyUI-packaged pruned FL2VA INT8 ConvRot base used by the dedicated 360 Orbit flow.',
  }),
  [modelKey('diffusion_models', 'minimax-h3-ref2va-Q4_0.gguf')]: createModelRecipe({
    filename: 'minimax-h3-ref2va-Q4_0.gguf',
    targetSubdir: 'diffusion_models',
    displayName: 'MiniMax H3 Ref2VA GGUF Q4_0',
    downloadUrl: hfResolve('molbal/MiniMax-H3-GGUF', 'minimax-h3-ref2va-Q4_0.gguf'),
    sourceUrl: hfBlob('molbal/MiniMax-H3-GGUF', 'minimax-h3-ref2va-Q4_0.gguf'),
    licenseUrl: 'https://huggingface.co/MiniMaxAI/MiniMax-H3/blob/main/LICENSE',
    sizeBytes: 11377542880,
    sha256: '737463c522b0f78ebe157df918c272935c2b61047ba7ae303008cfc84ba81644',
    notes: 'Q4 Ref2VA model shared by the CANVAS H3 Character Sheet and Reference Video to Video flows. It reuses the existing H3 GGUF encoder, mmproj, and VAEs. MiniMax H3 uses its own community license.',
  }),
  [modelKey('diffusion_models', 'minimax_h3_fl2va_pruned_fp8_Q4_0.gguf')]: createModelRecipe({
    filename: 'minimax_h3_fl2va_pruned_fp8_Q4_0.gguf',
    targetSubdir: 'diffusion_models',
    displayName: 'MiniMax H3 FL2VA GGUF Q4_0',
    downloadUrl: hfResolve('molbal/MiniMax-H3-GGUF', 'minimax_h3_fl2va_pruned_fp8_Q4_0.gguf'),
    sourceUrl: hfBlob('molbal/MiniMax-H3-GGUF', 'minimax_h3_fl2va_pruned_fp8_Q4_0.gguf'),
    licenseUrl: 'https://huggingface.co/MiniMaxAI/MiniMax-H3/blob/main/LICENSE',
    notes: 'Default GGUF diffusion model for the CANVAS MiniMax H3 image-to-video flow. MiniMax H3 uses its own community license.',
  }),
  [modelKey('text_encoders', 'MiniMax-H3-encoder-Q4_K_M.gguf')]: createModelRecipe({
    filename: 'MiniMax-H3-encoder-Q4_K_M.gguf',
    targetSubdir: 'text_encoders',
    displayName: 'MiniMax H3 text encoder GGUF Q4_K_M',
    downloadUrl: hfResolve('joeygambino/MiniMax-H3-encoder-GGUF', 'MiniMax-H3-encoder-Q4_K_M.gguf'),
    sourceUrl: hfBlob('joeygambino/MiniMax-H3-encoder-GGUF', 'MiniMax-H3-encoder-Q4_K_M.gguf'),
    licenseUrl: 'https://huggingface.co/MiniMaxAI/MiniMax-H3/blob/main/LICENSE',
    notes: 'GGUF text encoder. Keep the matching mmproj sidecar in the same text_encoders folder.',
  }),
  [modelKey('text_encoders', 'MiniMax-H3-encoder-mmproj-F16.gguf')]: createModelRecipe({
    filename: 'MiniMax-H3-encoder-mmproj-F16.gguf',
    targetSubdir: 'text_encoders',
    displayName: 'MiniMax H3 encoder vision sidecar F16',
    downloadUrl: hfResolve('joeygambino/MiniMax-H3-encoder-GGUF', 'MiniMax-H3-encoder-mmproj-F16.gguf'),
    sourceUrl: hfBlob('joeygambino/MiniMax-H3-encoder-GGUF', 'MiniMax-H3-encoder-mmproj-F16.gguf'),
    licenseUrl: 'https://huggingface.co/MiniMaxAI/MiniMax-H3/blob/main/LICENSE',
    notes: 'Vision projection sidecar paired explicitly with the GGUF text encoder.',
  }),
  [modelKey('vae', 'minimax_h3_video_vae_fp16.safetensors')]: createModelRecipe({
    filename: 'minimax_h3_video_vae_fp16.safetensors',
    targetSubdir: 'vae',
    displayName: 'MiniMax H3 video VAE FP16',
    downloadUrl: hfResolve('Comfy-Org/MiniMax-H3', 'vae/minimax_h3_video_vae_fp16.safetensors'),
    sourceUrl: hfBlob('Comfy-Org/MiniMax-H3', 'vae/minimax_h3_video_vae_fp16.safetensors'),
    licenseUrl: 'https://huggingface.co/MiniMaxAI/MiniMax-H3/blob/main/LICENSE',
    notes: 'Official ComfyUI-packaged video VAE for MiniMax H3.',
  }),
  [modelKey('diffusion_models', 'minimax_h3_fused_refdelta_r1024_turbo8_mystic07_int8_convrot.safetensors')]: createModelRecipe({
    filename: 'minimax_h3_fused_refdelta_r1024_turbo8_mystic07_int8_convrot.safetensors', targetSubdir: 'diffusion_models', displayName: 'Fast MiniMax H3 fused Turbo/Mystic INT8',
    downloadUrl: hfResolve('MATLOWAI/minimax-h3-fused-turbo-int8-convrot', 'diffusion_models/minimax_h3_fused_refdelta_r1024_turbo8_mystic07_int8_convrot.safetensors'),
    sourceUrl: hfBlob('MATLOWAI/minimax-h3-fused-turbo-int8-convrot', 'diffusion_models/minimax_h3_fused_refdelta_r1024_turbo8_mystic07_int8_convrot.safetensors'),
    licenseUrl: 'https://huggingface.co/MiniMaxAI/MiniMax-H3/blob/main/LICENSE',
    sizeBytes: 20980178976, sha256: '4262e4e9963c553fa00016bbe83961407a4fc0a888be95fd836c8d4f2304e48b',
  }),
  [modelKey('vae', 'minimax_h3_video_vae_int8_convrot.safetensors')]: createModelRecipe({
    filename: 'minimax_h3_video_vae_int8_convrot.safetensors', targetSubdir: 'vae', displayName: 'MiniMax H3 video VAE INT8 ConvRot',
    downloadUrl: hfResolve('Kijai/MiniMax-H3-experimental', 'minimax_h3_video_vae_int8_convrot.safetensors'),
    sourceUrl: hfBlob('Kijai/MiniMax-H3-experimental', 'minimax_h3_video_vae_int8_convrot.safetensors'),
    licenseUrl: 'https://huggingface.co/MiniMaxAI/MiniMax-H3/blob/main/LICENSE',
    sizeBytes: 3171670912, sha256: '9bb2d96f218c76babd85e0611b85ca8fb330a90546c01a0005e8a58a59593410',
  }),
  [modelKey('text_encoders', 'qwen3vl_32b_minimax_h3_nvfp4_awq.safetensors')]: createModelRecipe({
    filename: 'qwen3vl_32b_minimax_h3_nvfp4_awq.safetensors', targetSubdir: 'text_encoders', displayName: 'MiniMax H3 Qwen3 VL NVFP4 AWQ',
    downloadUrl: hfResolve('Comfy-Org/MiniMax-H3', 'text_encoders/qwen3vl_32b_minimax_h3_nvfp4_awq.safetensors'),
    sourceUrl: hfBlob('Comfy-Org/MiniMax-H3', 'text_encoders/qwen3vl_32b_minimax_h3_nvfp4_awq.safetensors'),
    licenseUrl: 'https://huggingface.co/MiniMaxAI/MiniMax-H3/blob/main/LICENSE',
    sizeBytes: 15687142551, sha256: '35a88d51044231fe332301d7a62aa81e3f2cba62febeb446e2c1e3e0ef76f2c6',
  }),
  [modelKey('vae', 'minimax_h3_audio_vae_fp32.safetensors')]: createModelRecipe({
    filename: 'minimax_h3_audio_vae_fp32.safetensors',
    targetSubdir: 'vae',
    displayName: 'MiniMax H3 audio VAE FP32',
    downloadUrl: hfResolve('Comfy-Org/MiniMax-H3', 'vae/minimax_h3_audio_vae_fp32.safetensors'),
    sourceUrl: hfBlob('Comfy-Org/MiniMax-H3', 'vae/minimax_h3_audio_vae_fp32.safetensors'),
    licenseUrl: 'https://huggingface.co/MiniMaxAI/MiniMax-H3/blob/main/LICENSE',
    sizeBytes: 605254808,
    sha256: '8e505d95dd1561d47abd43d4238fd40d9bb1ae9e147ed0a4cba778d76ae4db48',
    notes: 'Official ComfyUI-packaged audio VAE for native stereo audio output.',
  }),
  [modelKey('loras', 'minimax_h3_fl2v_turbo_8step_v1.0_comfyui_bf16.safetensors')]: createModelRecipe({
    filename: 'minimax_h3_fl2v_turbo_8step_v1.0_comfyui_bf16.safetensors',
    targetSubdir: 'loras',
    displayName: 'MiniMax H3 FL2V Turbo 8-step LoRA',
    downloadUrl: hfResolve('Comfy-Org/MiniMax-H3', 'loras/minimax_h3_fl2v_turbo_8step_v1.0_comfyui_bf16.safetensors'),
    sourceUrl: hfBlob('Comfy-Org/MiniMax-H3', 'loras/minimax_h3_fl2v_turbo_8step_v1.0_comfyui_bf16.safetensors'),
    licenseUrl: 'https://huggingface.co/lightx2v/Minimax-h3-Turbo',
    notes: 'Officially packaged LightX2V Turbo LoRA used to reduce the default CANVAS flow to eight sampling steps.',
  }),
  [modelKey('loras', 'MiniMax-H3-Ref2VA-Acc-8Step_pruned_comfy.safetensors')]: createModelRecipe({
    filename: 'MiniMax-H3-Ref2VA-Acc-8Step_pruned_comfy.safetensors',
    targetSubdir: 'loras',
    displayName: 'Kijai MiniMax H3 Ref2VA PDD Acc 8-step (pruned)',
    downloadUrl: hfResolve('Kijai/MiniMax-H3-experimental', 'loras/MiniMax-H3-Ref2VA-Acc-8Step_pruned_comfy.safetensors'),
    sourceUrl: hfBlob('Kijai/MiniMax-H3-experimental', 'loras/MiniMax-H3-Ref2VA-Acc-8Step_pruned_comfy.safetensors'),
    licenseUrl: 'https://huggingface.co/MiniMaxAI/MiniMax-H3/blob/main/LICENSE',
    sizeBytes: 1725921392,
    sha256: '6f18e1c2eccb14b37322607730f26b16bf1169b56cd098ea006cffaec43d1e39',
    notes: 'PDD acceleration LoRA matched to the pruned Ref2VA GGUF base. Use only at strength 1.0 with Euler/simple, 8 steps, CFG 1, and MiniMax H3 video/audio sigma shifts 12/3. Do not stack with another distillation LoRA.',
  }),
  [modelKey('loras', 'h3_character_swap_pro4500_1000.safetensors')]: createModelRecipe({
    filename: 'h3_character_swap_pro4500_1000.safetensors',
    targetSubdir: 'loras',
    displayName: 'Akatz MiniMax H3 Character Swap LoRA v1 (1000-step)',
    downloadUrl: hfResolve('akatz-ai/MiniMax-H3-Character-Swap-LoRA', 'h3_character_swap_pro4500_1000.safetensors'),
    sourceUrl: hfBlob('akatz-ai/MiniMax-H3-Character-Swap-LoRA', 'h3_character_swap_pro4500_1000.safetensors'),
    licenseUrl: 'https://huggingface.co/akatz-ai/MiniMax-H3-Character-Swap-LoRA/blob/main/LICENSE',
    sizeBytes: 155110320,
    sha256: '4b2a3f420ae804c0aa3422761ff84dbd1bf52eef6900ffab6d2e66df63cb4e79',
    notes: 'Experimental Ref2VA character-replacement adapter. Use alone at strength 1.0 with one source video and one replacement image. The beginner CANVAS preset is intentionally limited to 4-5 second shots at 24 fps and does not stack a Turbo LoRA.',
  }),
  [modelKey('loras', 'minimax_h3_flf2v_lora_v1.safetensors')]: createModelRecipe({
    filename: 'minimax_h3_flf2v_lora_v1.safetensors',
    targetSubdir: 'loras',
    displayName: 'Pablo Dawson MiniMax H3 360 Orbit LoRA v1',
    downloadUrl: 'https://huggingface.co/pablodawson/MiniMax-H3-360-Orbit-LoRA/resolve/5ddbc2dbbe95edbbdaf5017c3e934b1d01791697/minimax_h3_flf2v_lora_v1.safetensors',
    sourceUrl: 'https://huggingface.co/pablodawson/MiniMax-H3-360-Orbit-LoRA/blob/5ddbc2dbbe95edbbdaf5017c3e934b1d01791697/minimax_h3_flf2v_lora_v1.safetensors',
    licenseUrl: 'https://huggingface.co/MiniMaxAI/MiniMax-H3/blob/main/LICENSE',
    sizeBytes: 155111424,
    sha256: '14f13e3effaf3e729fdc0c97680344aa63f473be0c55963f963d718b3db2a4d4',
    notes: 'Commit-pinned experimental FL2VA orbit adapter. Use alone at strength 1.0 with the same 768x768 image as first and last frame, 73 frames, 24 fps, 28 steps, no CFG, and no audio.',
  }),
  [modelKey('loras', 'handheld_h3_100.safetensors')]: createModelRecipe({
    filename: 'handheld_h3_100.safetensors',
    targetSubdir: 'loras',
    displayName: 'neph1 MiniMax H3 Handheld Shaky Camera',
    downloadUrl: 'https://huggingface.co/neph1/minimax_h3_handheld_shaky_camera/resolve/c089b7833cbdffc05bdf17b188e7d7a4aa9e3d88/handheld_h3_100.safetensors',
    sourceUrl: 'https://huggingface.co/neph1/minimax_h3_handheld_shaky_camera/blob/c089b7833cbdffc05bdf17b188e7d7a4aa9e3d88/handheld_h3_100.safetensors',
    licenseUrl: 'https://huggingface.co/MiniMaxAI/MiniMax-H3/blob/main/LICENSE',
    sizeBytes: 77580048,
    sha256: 'd56360bc9de18abec4298518ed630167ee4a3f64a7dbbc8bc0c2259d33f74069',
    notes: 'Commit-pinned experimental MiniMax H3 camera-motion LoRA mirrored from Civitai model version 3343481. The publisher showcase uses about 1.7 strength and does not guarantee compatibility with other LoRAs.',
  }),
  [modelKey('loras', 'SexGod_NaughtyTimes_v3_rank64_pruned_NOADALN.safetensors')]: createModelRecipe({
    filename: 'SexGod_NaughtyTimes_v3_rank64_pruned_NOADALN.safetensors', targetSubdir: 'loras', displayName: 'NaughtyTimes MiniMax H3 v3 rank-64 (pruned)',
    downloadUrl: hfResolve('SexGod1979/NaughtyTimes-MiniMax-H3', 'SexGod_NaughtyTimes_v3_rank64_pruned_NOADALN.safetensors'),
    sourceUrl: hfBlob('SexGod1979/NaughtyTimes-MiniMax-H3', 'SexGod_NaughtyTimes_v3_rank64_pruned_NOADALN.safetensors'),
    licenseUrl: 'https://huggingface.co/SexGod1979/NaughtyTimes-MiniMax-H3',
    notes: 'Published pruned_NOADALN variant for the pruned FL2VA preset.',
  }),
  [modelKey('loras', 'PinkFluffyBunny-unpruned-v2-rank128.safetensors')]: createModelRecipe({
    filename: 'PinkFluffyBunny-unpruned-v2-rank128.safetensors',
    targetSubdir: 'loras',
    displayName: 'PinkFluffyBunny MiniMax H3 FL2VA v2 rank-128',
    downloadUrl: hfResolve('SexGod1979/PinkFluffyBunny-MiniMax-H3', 'PinkFluffyBunny-unpruned-fl2va-v2-rank128.safetensors'),
    sourceUrl: hfBlob('SexGod1979/PinkFluffyBunny-MiniMax-H3', 'PinkFluffyBunny-unpruned-fl2va-v2-rank128.safetensors'),
    licenseUrl: 'https://huggingface.co/SexGod1979/PinkFluffyBunny-MiniMax-H3',
    sizeBytes: 1121253992,
    sha256: '6f3b80b901b04813d76bfc2c1d38789541eefcc4a6ade93b645fdad82f1540d6',
    notes: 'NSFW FL2VA LoRA. The local legacy filename is retained so an existing Downloads copy can be installed without renaming. Do not stack with Turbo.',
  }),
  [modelKey('loras', 'AfterMidnight_ref2va_h3_sexytime_rank64-v1.2.safetensors')]: createModelRecipe({
    filename: 'AfterMidnight_ref2va_h3_sexytime_rank64-v1.2.safetensors',
    targetSubdir: 'loras',
    displayName: 'AfterMidnight MiniMax H3 Ref2VA sexytime rank-64 v1.2',
    downloadUrl: hfResolve('SexGod1979/AfterMidnight-MiniMax-H3-NSFW', 'AfterMidnight_ref2va_h3_sexytime_rank64-v1.2.safetensors'),
    sourceUrl: hfBlob('SexGod1979/AfterMidnight-MiniMax-H3-NSFW', 'AfterMidnight_ref2va_h3_sexytime_rank64-v1.2.safetensors'),
    licenseUrl: 'https://huggingface.co/SexGod1979/AfterMidnight-MiniMax-H3-NSFW/blob/main/README.md',
    sizeBytes: 1192828320,
    sha256: '82226a7c7f0b4631092f9270fa33d078c985a2d757895fcbe8f3fca8881bef59',
    notes: 'Ref2VA NSFW LoRA. Use alone at strength 1.0 with Euler sampler and beta scheduler as required by the author.',
  }),
  [modelKey('loras', 'minimax-h3_fl2v_8Step_motion_enhancer.safetensors')]: createModelRecipe({
    filename: 'minimax-h3_fl2v_8Step_motion_enhancer.safetensors',
    targetSubdir: 'loras',
    displayName: 'MiniMax H3 FL2V 8-step Motion Enhancer',
    downloadUrl: hfResolve('rzgar/minimax-h3_fl2v_8Step_motion_enhancer', 'minimax-h3_fl2v_8Step_motion_enhancer.safetensors'),
    sourceUrl: hfBlob('rzgar/minimax-h3_fl2v_8Step_motion_enhancer', 'minimax-h3_fl2v_8Step_motion_enhancer.safetensors'),
    licenseUrl: 'https://huggingface.co/rzgar/minimax-h3_fl2v_8Step_motion_enhancer',
    notes: 'Dedicated eight-step NSFW motion LoRA. Replaces the vanilla LightX2V adapter.',
  }),
  [modelKey('checkpoints', 'irodori-tts-500m-v3.safetensors')]: createModelRecipe({
    filename: 'irodori-tts-500m-v3.safetensors',
    targetSubdir: 'checkpoints',
    displayName: 'Irodori-TTS 500M v3',
    downloadUrl: hfResolve('Aratako/Irodori-TTS-500M-v3', 'model.safetensors'),
    sourceUrl: hfBlob('Aratako/Irodori-TTS-500M-v3', 'model.safetensors'),
    licenseUrl: 'https://huggingface.co/Aratako/Irodori-TTS-500M-v3',
    sizeBytes: 2048269748,
    sha256: '8dbd537f8edebcce7fddc2a093fd8bd649cfb87741800ddf417f52bdfeb55b70',
    notes: 'Latest local Irodori-TTS v3 checkpoint used by Short Film Creation. Existing copies in checkpoint subfolders are detected by filename.',
  }),
  [modelKey('checkpoints', 'irodori-tts-v4.1-anime.safetensors')]: createModelRecipe({
    filename: 'irodori-tts-v4.1-anime.safetensors',
    targetSubdir: 'checkpoints',
    displayName: 'Irodori-TTS v4.1 Anime',
    downloadUrl: hfResolve('phasefield-audio/Irodori-TTS-v4.1-Anime', 'model.safetensors'),
    sourceUrl: hfBlob('phasefield-audio/Irodori-TTS-v4.1-Anime', 'model.safetensors'),
    licenseUrl: 'https://huggingface.co/phasefield-audio/Irodori-TTS-v4.1-Anime',
    sizeBytes: 3064295596,
    sha256: '5630aa0a661930ff678a1d1f1893876e24520f4776d4fcc25ca54e6ab9f41f37',
    notes: 'Anime-style Japanese Irodori v4.1 checkpoint. Supports the existing Irodori inference interface; caption and emoji behavior may differ from the base model.',
  }),
  [modelKey('checkpoints', 'irodori-tts-500m-v2-VoiceDesign.safetensors')]: createModelRecipe({
    filename: 'irodori-tts-500m-v2-VoiceDesign.safetensors',
    targetSubdir: 'checkpoints',
    displayName: 'Irodori-TTS 500M v2 VoiceDesign',
    downloadUrl: hfResolve('Aratako/Irodori-TTS-500M-v2-VoiceDesign', 'model.safetensors'),
    sourceUrl: hfBlob('Aratako/Irodori-TTS-500M-v2-VoiceDesign', 'model.safetensors'),
    licenseUrl: 'https://huggingface.co/Aratako/Irodori-TTS-500M-v2-VoiceDesign',
    sizeBytes: 2045071384,
    sha256: '8b703c28e88f160dee0258b1136f8fe1ea68c063b45fc28375b5a134d6ce1131',
    notes: 'Japanese VoiceDesign checkpoint for reference-free voice, tone, emotion, and speaking-style prompts.',
  }),
  [modelKey('vae', 'ace_1.5_vae.safetensors')]: createModelRecipe({
    filename: 'ace_1.5_vae.safetensors',
    targetSubdir: 'vae',
    displayName: 'ACE-Step 1.5 VAE',
    downloadUrl: hfResolve('Comfy-Org/ace_step_1.5_ComfyUI_files', 'split_files/vae/ace_1.5_vae.safetensors'),
    sourceUrl: hfBlob('Comfy-Org/ace_step_1.5_ComfyUI_files', 'split_files/vae/ace_1.5_vae.safetensors'),
    licenseUrl: 'https://huggingface.co/ACE-Step/Ace-Step1.5',
    sizeBytes: 337431732,
    notes: 'Required by the built-in music generation workflow.',
  }),
  [modelKey('text_encoders', 'qwen_0.6b_ace15.safetensors')]: createModelRecipe({
    filename: 'qwen_0.6b_ace15.safetensors',
    targetSubdir: 'text_encoders',
    displayName: 'ACE-Step 1.5 Qwen 0.6B text encoder',
    downloadUrl: hfResolve('Comfy-Org/ace_step_1.5_ComfyUI_files', 'split_files/text_encoders/qwen_0.6b_ace15.safetensors'),
    sourceUrl: hfBlob('Comfy-Org/ace_step_1.5_ComfyUI_files', 'split_files/text_encoders/qwen_0.6b_ace15.safetensors'),
    licenseUrl: 'https://huggingface.co/ACE-Step/Ace-Step1.5',
    // Size/checksum not curated yet — the download still works; it just skips
    // hash verification and shows "Unknown size" until confirmed on HF.
    notes: 'Text encoder for the built-in ACE-Step 1.5 music workflow (DualCLIPLoader).',
  }),
  [modelKey('text_encoders', 'qwen_1.7b_ace15.safetensors')]: createModelRecipe({
    filename: 'qwen_1.7b_ace15.safetensors',
    targetSubdir: 'text_encoders',
    displayName: 'ACE-Step 1.5 Qwen 1.7B text encoder',
    downloadUrl: hfResolve('Comfy-Org/ace_step_1.5_ComfyUI_files', 'split_files/text_encoders/qwen_1.7b_ace15.safetensors'),
    sourceUrl: hfBlob('Comfy-Org/ace_step_1.5_ComfyUI_files', 'split_files/text_encoders/qwen_1.7b_ace15.safetensors'),
    licenseUrl: 'https://huggingface.co/ACE-Step/Ace-Step1.5',
    notes: 'Text encoder for the built-in ACE-Step 1.5 music workflow (DualCLIPLoader).',
  }),
  [modelKey('diffusion_models', 'acestep_v1.5_turbo.safetensors')]: createModelRecipe({
    filename: 'acestep_v1.5_turbo.safetensors',
    targetSubdir: 'diffusion_models',
    displayName: 'ACE-Step 1.5 Turbo diffusion model',
    downloadUrl: hfResolve('Comfy-Org/ace_step_1.5_ComfyUI_files', 'split_files/diffusion_models/acestep_v1.5_turbo.safetensors'),
    sourceUrl: hfBlob('Comfy-Org/ace_step_1.5_ComfyUI_files', 'split_files/diffusion_models/acestep_v1.5_turbo.safetensors'),
    licenseUrl: 'https://huggingface.co/ACE-Step/Ace-Step1.5',
    sizeBytes: 4790000000,
    notes: 'Required by the built-in music generation workflow.',
  }),
  [modelKey('vae', 'ae.safetensors')]: createModelRecipe({
    filename: 'ae.safetensors',
    targetSubdir: 'vae',
    displayName: 'Z Image Turbo VAE',
    downloadUrl: hfResolve('Comfy-Org/z_image_turbo', 'split_files/vae/ae.safetensors'),
    sourceUrl: hfBlob('Comfy-Org/z_image_turbo', 'split_files/vae/ae.safetensors'),
    licenseUrl: 'https://huggingface.co/Tongyi-MAI/Z-Image-Turbo',
    sizeBytes: 335304388,
    sha256: 'afc8e28272cd15db3919bacdb6918ce9c1ed22e96cb12c4d5ed0fba823529e38',
    notes: 'Flux-compatible VAE used by Z Image Turbo.',
  }),
  [modelKey('text_encoders', 'gemma_3_12B_it_fp4_mixed.safetensors')]: createModelRecipe({
    filename: 'gemma_3_12B_it_fp4_mixed.safetensors',
    targetSubdir: 'text_encoders',
    displayName: 'Gemma 3 12B FP4 mixed text encoder',
    downloadUrl: hfResolve('Comfy-Org/ltx-2', 'split_files/text_encoders/gemma_3_12B_it_fp4_mixed.safetensors'),
    sourceUrl: hfBlob('Comfy-Org/ltx-2', 'split_files/text_encoders/gemma_3_12B_it_fp4_mixed.safetensors'),
    licenseUrl: 'https://huggingface.co/google/gemma-3-12b-it-qat-q4_0-unquantized',
    sizeBytes: 9447702218,
    notes: 'Used by the LTX 2.3 workflow text encoder loader.',
  }),
  [modelKey('checkpoints', 'ltx-2.3-22b-dev-fp8.safetensors')]: createModelRecipe({
    filename: 'ltx-2.3-22b-dev-fp8.safetensors',
    targetSubdir: 'checkpoints',
    displayName: 'LTX 2.3 22B FP8 checkpoint',
    downloadUrl: hfResolve('Lightricks/LTX-2.3-fp8', 'ltx-2.3-22b-dev-fp8.safetensors'),
    sourceUrl: hfBlob('Lightricks/LTX-2.3-fp8', 'ltx-2.3-22b-dev-fp8.safetensors'),
    licenseUrl: 'https://huggingface.co/Lightricks/LTX-2.3-fp8',
    sizeBytes: 29145431166,
    notes: 'Main checkpoint used by the bundled LTX 2.3 workflow.',
  }),
  [modelKey('loras', 'ltx-2.3-22b-distilled-lora-384.safetensors')]: createModelRecipe({
    filename: 'ltx-2.3-22b-distilled-lora-384.safetensors',
    targetSubdir: 'loras',
    displayName: 'LTX 2.3 distilled LoRA',
    downloadUrl: hfResolve('Lightricks/LTX-2.3', 'ltx-2.3-22b-distilled-lora-384-1.1.safetensors'),
    sourceUrl: hfBlob('Lightricks/LTX-2.3', 'ltx-2.3-22b-distilled-lora-384-1.1.safetensors'),
    licenseUrl: 'https://huggingface.co/Lightricks/LTX-2.3',
    sizeBytes: 7605507256,
    notes: 'Downloaded from the official Lightricks repo and saved under the workflow-expected filename.',
  }),
  [modelKey('loras', 'ltx_2.3_22b_distilled_1.1_lora_dynamic_fro09_avg_rank_111_bf16.safetensors')]: createModelRecipe({
    filename: 'ltx_2.3_22b_distilled_1.1_lora_dynamic_fro09_avg_rank_111_bf16.safetensors',
    targetSubdir: 'loras',
    displayName: 'LTX 2.3 distilled dynamic LoRA',
    downloadUrl: hfResolve('Lightricks/LTX-2.3', 'ltx-2.3-22b-distilled-lora-384-1.1.safetensors'),
    sourceUrl: hfBlob('Lightricks/LTX-2.3', 'ltx-2.3-22b-distilled-lora-384-1.1.safetensors'),
    licenseUrl: 'https://huggingface.co/Lightricks/LTX-2.3',
    sizeBytes: 7605507256,
    notes: 'Downloaded from the official Lightricks repo and saved under the filename expected by the bundled image-to-video workflow.',
  }),
  [modelKey('latent_upscale_models', 'ltx-2.3-spatial-upscaler-x2-1.1.safetensors')]: createModelRecipe({
    filename: 'ltx-2.3-spatial-upscaler-x2-1.1.safetensors',
    targetSubdir: 'latent_upscale_models',
    displayName: 'LTX 2.3 spatial upscaler x2',
    downloadUrl: hfResolve('Lightricks/LTX-2.3', 'ltx-2.3-spatial-upscaler-x2-1.1.safetensors'),
    sourceUrl: hfBlob('Lightricks/LTX-2.3', 'ltx-2.3-spatial-upscaler-x2-1.1.safetensors'),
    licenseUrl: 'https://huggingface.co/Lightricks/LTX-2.3',
    sizeBytes: 995743560,
    notes: 'Required for the bundled LTX 2.3 upscaling step.',
  }),
  [modelKey('text_encoders', 'qwen_2.5_vl_7b_fp8_scaled.safetensors')]: createModelRecipe({
    filename: 'qwen_2.5_vl_7b_fp8_scaled.safetensors',
    targetSubdir: 'text_encoders',
    displayName: 'Qwen 2.5 VL 7B FP8 text encoder',
    downloadUrl: hfResolve('Comfy-Org/Qwen-Image_ComfyUI', 'split_files/text_encoders/qwen_2.5_vl_7b_fp8_scaled.safetensors'),
    sourceUrl: hfBlob('Comfy-Org/Qwen-Image_ComfyUI', 'split_files/text_encoders/qwen_2.5_vl_7b_fp8_scaled.safetensors'),
    licenseUrl: 'https://huggingface.co/Qwen/Qwen-Image',
    sizeBytes: 9380000000,
    notes: 'Shared by Qwen image edit and multiple-angle workflows.',
  }),
  [modelKey('text_encoders', 'Qwen2.5-VL-7B-Instruct-Q4_K_M.gguf')]: createModelRecipe({
    filename: 'Qwen2.5-VL-7B-Instruct-Q4_K_M.gguf',
    targetSubdir: 'text_encoders',
    displayName: 'Qwen 2.5 VL 7B GGUF Q4_K_M text encoder',
    downloadUrl: hfResolve('ggml-org/Qwen2.5-VL-7B-Instruct-GGUF', 'Qwen2.5-VL-7B-Instruct-Q4_K_M.gguf'),
    sourceUrl: hfBlob('ggml-org/Qwen2.5-VL-7B-Instruct-GGUF', 'Qwen2.5-VL-7B-Instruct-Q4_K_M.gguf'),
    licenseUrl: 'https://huggingface.co/Qwen/Qwen2.5-VL-7B-Instruct',
    sizeBytes: 4683072032,
    sha256: '9258bf05b12686d097ff3b6b18d968ab393649780aa2b3cd67fec43d50554392',
    notes: 'GGUF text encoder for Qwen Image Edit 2509. Keep its matching mmproj in the same text_encoders folder.',
  }),
  [modelKey('text_encoders', 'Qwen2.5-VL-7B-Instruct-mmproj-BF16.gguf')]: createModelRecipe({
    filename: 'Qwen2.5-VL-7B-Instruct-mmproj-BF16.gguf',
    targetSubdir: 'text_encoders',
    displayName: 'Qwen 2.5 VL 7B mmproj BF16',
    downloadUrl: hfResolve('QuantStack/Qwen-Image-Edit-GGUF', 'mmproj/Qwen2.5-VL-7B-Instruct-mmproj-BF16.gguf'),
    sourceUrl: hfBlob('QuantStack/Qwen-Image-Edit-GGUF', 'mmproj/Qwen2.5-VL-7B-Instruct-mmproj-BF16.gguf'),
    licenseUrl: 'https://huggingface.co/Qwen/Qwen2.5-VL-7B-Instruct',
    sizeBytes: 1354163040,
    sha256: 'f0edf43c09b69d6e5dd24262f33b356a1e9dd978e7c3299b3e69141fcbb87553',
    notes: 'Automatically discovered by ComfyUI-GGUF when stored beside the matching Qwen 2.5 VL GGUF encoder.',
  }),
  [modelKey('text_encoders', 'qwen_3_4b.safetensors')]: createModelRecipe({
    filename: 'qwen_3_4b.safetensors',
    targetSubdir: 'text_encoders',
    displayName: 'Qwen 3 4B text encoder',
    downloadUrl: hfResolve('Comfy-Org/z_image_turbo', 'split_files/text_encoders/qwen_3_4b.safetensors'),
    sourceUrl: hfBlob('Comfy-Org/z_image_turbo', 'split_files/text_encoders/qwen_3_4b.safetensors'),
    licenseUrl: 'https://huggingface.co/Tongyi-MAI/Z-Image-Turbo',
    sizeBytes: 8040000000,
    notes: 'Text encoder used by Z Image Turbo.',
  }),
  [modelKey('text_encoders', 'qwen3vl_4b_fp8_scaled.safetensors')]: createModelRecipe({
    filename: 'qwen3vl_4b_fp8_scaled.safetensors',
    targetSubdir: 'text_encoders',
    displayName: 'Krea 2 Qwen3-VL 4B FP8 text encoder',
    downloadUrl: hfResolve('Comfy-Org/Krea-2', 'text_encoders/qwen3vl_4b_fp8_scaled.safetensors'),
    sourceUrl: hfBlob('Comfy-Org/Krea-2', 'text_encoders/qwen3vl_4b_fp8_scaled.safetensors'),
    licenseUrl: 'https://huggingface.co/Comfy-Org/Krea-2/blob/main/LICENSE.pdf',
    sizeBytes: 5242467968,
    sha256: '54bd5144df0bbc25dd6ccadfcb826b521445a1b06ae5a42570bdd2974ca87094',
    notes: 'Official Comfy-Org Krea 2 FP8 text encoder.',
  }),
  [modelKey('diffusion_models', 'darkBeastH3Director_darkBeastKREA2FP8_2958418.safetensors')]: createModelRecipe({
    filename: 'darkBeastH3Director_darkBeastKREA2FP8_2958418.safetensors',
    targetSubdir: 'diffusion_models',
    displayName: 'Dark Beast KREA 2 FP8 (Civitai version 3078453)',
    downloadUrl: '',
    sourceUrl: 'https://civitai.red/models/2242173/dark-beast-or-h3-director-edition?modelVersionId=3078453',
    licenseUrl: 'https://civitai.red/models/2242173/dark-beast-or-h3-director-edition?modelVersionId=3078453',
    sizeBytes: 12820167396,
    sha256: '0C005BB2DA4AA249CEB4E9A90C3914DA9280660CF480F780C7386B92A8CFFC1B',
    requiresAccessApproval: true,
    notes: 'Install through Generate > Community with a Civitai API key. The exact linked version is Krea 2, not MiniMax H3.',
  }),
  [modelKey('diffusion_models', 'harukiMIX_kr2V20Int8Convrot.safetensors')]: createModelRecipe({
    filename: 'harukiMIX_kr2V20Int8Convrot.safetensors',
    targetSubdir: 'diffusion_models',
    displayName: 'HARUKI_MIX KR2 V2.0 INT8 ConvRot (Civitai version 3188234)',
    downloadUrl: '',
    sourceUrl: 'https://civitai.red/models/856375/harukimix?modelVersionId=3188234',
    licenseUrl: 'https://civitai.red/models/856375/harukimix?modelVersionId=3188234',
    sizeBytes: 13492078408,
    sha256: '7B903F38BC8A6F9E988A46F373B70BEAF4FB70534A7A94FB94F300D461361BB9',
    requiresAccessApproval: true,
    notes: 'Install through Generate > Community with a Civitai API key and the external-model consent gate. Do not redistribute, merge, or use it in a paid generation service.',
  }),
  [modelKey('text_encoders', 'Qwen3-4B-Q4_K_M.gguf')]: createModelRecipe({
    filename: 'Qwen3-4B-Q4_K_M.gguf',
    targetSubdir: 'text_encoders',
    displayName: 'Qwen 3 4B GGUF Q4_K_M text encoder',
    downloadUrl: hfResolve('unsloth/Qwen3-4B-GGUF', 'Qwen3-4B-Q4_K_M.gguf'),
    sourceUrl: hfBlob('unsloth/Qwen3-4B-GGUF', 'Qwen3-4B-Q4_K_M.gguf'),
    licenseUrl: 'https://huggingface.co/Qwen/Qwen3-4B',
    sizeBytes: 2497281312,
    sha256: 'f6f851777709861056efcdad3af01da38b31223a3ba26e61a4f8bf3a2195813a',
    notes: 'Memory-efficient Q4_K_M text encoder used by the bundled Z Image Turbo GGUF workflow.',
  }),
  [modelKey('diffusion_models', 'qwen_image_edit_2509_fp8_e4m3fn.safetensors')]: createModelRecipe({
    filename: 'qwen_image_edit_2509_fp8_e4m3fn.safetensors',
    targetSubdir: 'diffusion_models',
    displayName: 'Qwen Image Edit 2509 FP8 diffusion model',
    downloadUrl: hfResolve('Comfy-Org/Qwen-Image-Edit_ComfyUI', 'split_files/diffusion_models/qwen_image_edit_2509_fp8_e4m3fn.safetensors'),
    sourceUrl: hfBlob('Comfy-Org/Qwen-Image-Edit_ComfyUI', 'split_files/diffusion_models/qwen_image_edit_2509_fp8_e4m3fn.safetensors'),
    licenseUrl: 'https://huggingface.co/Qwen/Qwen-Image-Edit-2509',
    sizeBytes: 20400000000,
    notes: 'Shared by Qwen image edit and multiple-angle workflows.',
  }),
  [modelKey('diffusion_models', 'Qwen-Image-Edit-2509-Q4_K_M.gguf')]: createModelRecipe({
    filename: 'Qwen-Image-Edit-2509-Q4_K_M.gguf',
    targetSubdir: 'diffusion_models',
    displayName: 'Qwen Image Edit 2509 GGUF Q4_K_M diffusion model',
    downloadUrl: hfResolve('QuantStack/Qwen-Image-Edit-2509-GGUF', 'Qwen-Image-Edit-2509-Q4_K_M.gguf'),
    sourceUrl: hfBlob('QuantStack/Qwen-Image-Edit-2509-GGUF', 'Qwen-Image-Edit-2509-Q4_K_M.gguf'),
    licenseUrl: 'https://huggingface.co/Qwen/Qwen-Image-Edit-2509',
    sizeBytes: 13065746976,
    sha256: '08f27cdf3e760edef5136ab0afdb9d3ed7a2799bd730b8d5cd9ecb291d808425',
    notes: 'Q4_K_M GGUF model used by the bundled Qwen Image Edit 2509 workflows.',
  }),
  [modelKey('diffusion_models', 'qwen-image-edit-2511-Q5_K_M.gguf')]: createModelRecipe({
    filename: 'qwen-image-edit-2511-Q5_K_M.gguf',
    targetSubdir: 'diffusion_models',
    displayName: 'Qwen Image Edit 2511 GGUF Q5_K_M diffusion model',
    downloadUrl: hfResolve('unsloth/Qwen-Image-Edit-2511-GGUF', 'qwen-image-edit-2511-Q5_K_M.gguf'),
    sourceUrl: hfBlob('unsloth/Qwen-Image-Edit-2511-GGUF', 'qwen-image-edit-2511-Q5_K_M.gguf'),
    licenseUrl: 'https://huggingface.co/Qwen/Qwen-Image-Edit-2511',
    sizeBytes: 15027501664,
    notes: 'Memory-efficient Qwen 2511 model used by the bundled multiple-angle workflows.',
  }),
  [modelKey('vae', 'qwen_image_vae.safetensors')]: createModelRecipe({
    filename: 'qwen_image_vae.safetensors',
    targetSubdir: 'vae',
    displayName: 'Qwen image VAE',
    downloadUrl: hfResolve('Comfy-Org/Qwen-Image_ComfyUI', 'split_files/vae/qwen_image_vae.safetensors'),
    sourceUrl: hfBlob('Comfy-Org/Qwen-Image_ComfyUI', 'split_files/vae/qwen_image_vae.safetensors'),
    licenseUrl: 'https://huggingface.co/Qwen/Qwen-Image',
    sizeBytes: 253806246,
    notes: 'Shared by Qwen image edit and multiple-angle workflows.',
  }),
  [modelKey('loras', 'Qwen-Edit-2509-Multiple-angles.safetensors')]: createModelRecipe({
    filename: 'Qwen-Edit-2509-Multiple-angles.safetensors',
    targetSubdir: 'loras',
    displayName: 'Qwen multiple-angles LoRA',
    downloadUrl: hfResolve('Comfy-Org/Qwen-Image-Edit_ComfyUI', 'split_files/loras/Qwen-Edit-2509-Multiple-angles.safetensors'),
    sourceUrl: hfBlob('Comfy-Org/Qwen-Image-Edit_ComfyUI', 'split_files/loras/Qwen-Edit-2509-Multiple-angles.safetensors'),
    licenseUrl: 'https://huggingface.co/dx8152/Qwen-Edit-2509-Multiple-angles',
    sizeBytes: 236117032,
    notes: 'Enables the bundled multi-angle helper workflows.',
  }),
  [modelKey('loras', 'Qwen-Image-Edit-2509-Lightning-4steps-V1.0-bf16.safetensors')]: createModelRecipe({
    filename: 'Qwen-Image-Edit-2509-Lightning-4steps-V1.0-bf16.safetensors',
    targetSubdir: 'loras',
    displayName: 'Qwen Image Edit lightning 4-step LoRA',
    downloadUrl: hfResolve('lightx2v/Qwen-Image-Lightning', 'Qwen-Image-Edit-2509/Qwen-Image-Edit-2509-Lightning-4steps-V1.0-bf16.safetensors'),
    sourceUrl: hfBlob('lightx2v/Qwen-Image-Lightning', 'Qwen-Image-Edit-2509/Qwen-Image-Edit-2509-Lightning-4steps-V1.0-bf16.safetensors'),
    licenseUrl: 'https://huggingface.co/lightx2v/Qwen-Image-Lightning',
    sizeBytes: 849608296,
    notes: 'Optional speed LoRA used by the bundled Qwen image edit workflow.',
  }),
  [modelKey('loras', 'Qwen-Image-Edit-2511-Lightning-4steps-V1.0-bf16.safetensors')]: createModelRecipe({
    filename: 'Qwen-Image-Edit-2511-Lightning-4steps-V1.0-bf16.safetensors',
    targetSubdir: 'loras',
    displayName: 'Qwen Image Edit 2511 Lightning 4-step LoRA',
    downloadUrl: hfResolve('lightx2v/Qwen-Image-Edit-2511-Lightning', 'Qwen-Image-Edit-2511-Lightning-4steps-V1.0-bf16.safetensors'),
    sourceUrl: hfBlob('lightx2v/Qwen-Image-Edit-2511-Lightning', 'Qwen-Image-Edit-2511-Lightning-4steps-V1.0-bf16.safetensors'),
    licenseUrl: 'https://huggingface.co/lightx2v/Qwen-Image-Edit-2511-Lightning',
    sizeBytes: 849608296,
    notes: 'Four-step acceleration LoRA for Qwen Image Edit 2511.',
  }),
  [modelKey('loras', 'qwen-image-edit-2511-multiple-angles-lora.safetensors')]: createModelRecipe({
    filename: 'qwen-image-edit-2511-multiple-angles-lora.safetensors',
    targetSubdir: 'loras',
    displayName: 'Qwen Image Edit 2511 Multiple Angles LoRA',
    downloadUrl: hfResolve('fal/Qwen-Image-Edit-2511-Multiple-Angles-LoRA', 'qwen-image-edit-2511-multiple-angles-lora.safetensors'),
    sourceUrl: hfBlob('fal/Qwen-Image-Edit-2511-Multiple-Angles-LoRA', 'qwen-image-edit-2511-multiple-angles-lora.safetensors'),
    licenseUrl: 'https://huggingface.co/fal/Qwen-Image-Edit-2511-Multiple-Angles-LoRA',
    sizeBytes: 295140688,
    notes: 'Provides 2511-native camera angle control with the required <sks> prompt format.',
  }),
  [modelKey('text_encoders', 'umt5_xxl_fp8_e4m3fn_scaled.safetensors')]: createModelRecipe({
    filename: 'umt5_xxl_fp8_e4m3fn_scaled.safetensors',
    targetSubdir: 'text_encoders',
    displayName: 'WAN UMT5 XXL FP8 text encoder',
    downloadUrl: hfResolve('Comfy-Org/Wan_2.2_ComfyUI_Repackaged', 'split_files/text_encoders/umt5_xxl_fp8_e4m3fn_scaled.safetensors'),
    sourceUrl: hfBlob('Comfy-Org/Wan_2.2_ComfyUI_Repackaged', 'split_files/text_encoders/umt5_xxl_fp8_e4m3fn_scaled.safetensors'),
    licenseUrl: 'https://huggingface.co/Wan-AI/Wan2.2-I2V-A14B',
    sizeBytes: 6735906897,
    notes: 'Text encoder for the bundled WAN 2.2 workflow.',
  }),
  [modelKey('diffusion_models', 'wan_1.3B_e10.safetensors')]: createModelRecipe({
    filename: 'wan_1.3B_e10.safetensors',
    targetSubdir: 'diffusion_models',
    displayName: 'NSFW Wan 1.3B e10 diffusion model',
    downloadUrl: hfResolve('NSFW-API/NSFW_Wan_1.3b', 'wan_1.3B_e10.safetensors'),
    sourceUrl: hfBlob('NSFW-API/NSFW_Wan_1.3b', 'wan_1.3B_e10.safetensors'),
    licenseUrl: 'https://huggingface.co/NSFW-API/NSFW_Wan_1.3b',
    sizeBytes: 2838095480,
    sha256: 'b0be4a5dded7594deb7c11bcb808dac86c79619ae73ca9917cd8f0447f203d80',
    notes: 'Requested legacy e10 full Wan 2.1 T2V checkpoint. The publisher warns that the original e4-e20 run can show anatomy degradation and currently recommends exp_e14 instead.',
  }),
  [modelKey('text_encoders', 'umt5-xxl-encoder-Q4_K_M.gguf')]: createModelRecipe({
    filename: 'umt5-xxl-encoder-Q4_K_M.gguf',
    targetSubdir: 'text_encoders',
    displayName: 'WAN UMT5 XXL GGUF Q4_K_M text encoder',
    downloadUrl: hfResolve('city96/umt5-xxl-encoder-gguf', 'umt5-xxl-encoder-Q4_K_M.gguf'),
    sourceUrl: hfBlob('city96/umt5-xxl-encoder-gguf', 'umt5-xxl-encoder-Q4_K_M.gguf'),
    licenseUrl: 'https://huggingface.co/google/umt5-xxl',
    sizeBytes: 3655145312,
    sha256: '17cf97a5bbbc60a646d6105b832b6f657ce904a8a1ad970e4b59df0c67584a40',
    notes: 'Shared Q4_K_M text encoder for the bundled WAN 2.2 I2V and T2V GGUF workflows.',
  }),
  [modelKey('diffusion_models', 'Wan2.2-I2V-A14B-HighNoise-Q4_K_M.gguf')]: createModelRecipe({
    filename: 'Wan2.2-I2V-A14B-HighNoise-Q4_K_M.gguf',
    targetSubdir: 'diffusion_models',
    displayName: 'WAN 2.2 I2V high-noise GGUF Q4_K_M expert',
    downloadUrl: hfResolve('QuantStack/Wan2.2-I2V-A14B-GGUF', 'HighNoise/Wan2.2-I2V-A14B-HighNoise-Q4_K_M.gguf'),
    sourceUrl: hfBlob('QuantStack/Wan2.2-I2V-A14B-GGUF', 'HighNoise/Wan2.2-I2V-A14B-HighNoise-Q4_K_M.gguf'),
    licenseUrl: 'https://huggingface.co/Wan-AI/Wan2.2-I2V-A14B',
    sizeBytes: 9651728896,
    sha256: '836250abfaa3411694e2c9cf3a0cc18265329d5156d81aa116d5366b0f8f02e7',
    notes: 'Q4_K_M high-noise MoE expert for the bundled local WAN 2.2 image-to-video workflow.',
  }),
  [modelKey('diffusion_models', 'Wan2.2-I2V-A14B-LowNoise-Q4_K_M.gguf')]: createModelRecipe({
    filename: 'Wan2.2-I2V-A14B-LowNoise-Q4_K_M.gguf',
    targetSubdir: 'diffusion_models',
    displayName: 'WAN 2.2 I2V low-noise GGUF Q4_K_M expert',
    downloadUrl: hfResolve('QuantStack/Wan2.2-I2V-A14B-GGUF', 'LowNoise/Wan2.2-I2V-A14B-LowNoise-Q4_K_M.gguf'),
    sourceUrl: hfBlob('QuantStack/Wan2.2-I2V-A14B-GGUF', 'LowNoise/Wan2.2-I2V-A14B-LowNoise-Q4_K_M.gguf'),
    licenseUrl: 'https://huggingface.co/Wan-AI/Wan2.2-I2V-A14B',
    sizeBytes: 9651728896,
    sha256: 'e2f98d834af009d035c6b0918268f2eba0aa8a63025ce942277e2384d40b0866',
    notes: 'Q4_K_M low-noise MoE expert for the bundled local WAN 2.2 image-to-video workflow.',
  }),
  [modelKey('diffusion_models', 'Wan2.2-T2V-A14B-HighNoise-Q4_K_M.gguf')]: createModelRecipe({
    filename: 'Wan2.2-T2V-A14B-HighNoise-Q4_K_M.gguf',
    targetSubdir: 'diffusion_models',
    displayName: 'WAN 2.2 T2V high-noise GGUF Q4_K_M expert',
    downloadUrl: hfResolve('QuantStack/Wan2.2-T2V-A14B-GGUF', 'HighNoise/Wan2.2-T2V-A14B-HighNoise-Q4_K_M.gguf'),
    sourceUrl: hfBlob('QuantStack/Wan2.2-T2V-A14B-GGUF', 'HighNoise/Wan2.2-T2V-A14B-HighNoise-Q4_K_M.gguf'),
    licenseUrl: 'https://huggingface.co/Wan-AI/Wan2.2-T2V-A14B',
    sizeBytes: 9650090496,
    sha256: 'e0c490c6e316fd91ff52034e4ca66b825717e33ff11624585c0ccfcb5d410c59',
    notes: 'Q4_K_M high-noise MoE expert for the bundled local WAN 2.2 text-to-video workflow.',
  }),
  [modelKey('diffusion_models', 'Wan2.2-T2V-A14B-LowNoise-Q4_K_M.gguf')]: createModelRecipe({
    filename: 'Wan2.2-T2V-A14B-LowNoise-Q4_K_M.gguf',
    targetSubdir: 'diffusion_models',
    displayName: 'WAN 2.2 T2V low-noise GGUF Q4_K_M expert',
    downloadUrl: hfResolve('QuantStack/Wan2.2-T2V-A14B-GGUF', 'LowNoise/Wan2.2-T2V-A14B-LowNoise-Q4_K_M.gguf'),
    sourceUrl: hfBlob('QuantStack/Wan2.2-T2V-A14B-GGUF', 'LowNoise/Wan2.2-T2V-A14B-LowNoise-Q4_K_M.gguf'),
    licenseUrl: 'https://huggingface.co/Wan-AI/Wan2.2-T2V-A14B',
    sizeBytes: 9650090496,
    sha256: '091a5bae02e14aa016bc9b10a7892efda4c629346b81c5dcebbe30ea2ac8923a',
    notes: 'Q4_K_M low-noise MoE expert for the bundled local WAN 2.2 text-to-video workflow.',
  }),
  [modelKey('diffusion_models', 'wan2.2_i2v_high_noise_14B_fp8_scaled.safetensors')]: createModelRecipe({
    filename: 'wan2.2_i2v_high_noise_14B_fp8_scaled.safetensors',
    targetSubdir: 'diffusion_models',
    displayName: 'WAN 2.2 high-noise expert diffusion model',
    downloadUrl: hfResolve('Comfy-Org/Wan_2.2_ComfyUI_Repackaged', 'split_files/diffusion_models/wan2.2_i2v_high_noise_14B_fp8_scaled.safetensors'),
    sourceUrl: hfBlob('Comfy-Org/Wan_2.2_ComfyUI_Repackaged', 'split_files/diffusion_models/wan2.2_i2v_high_noise_14B_fp8_scaled.safetensors'),
    licenseUrl: 'https://huggingface.co/Wan-AI/Wan2.2-I2V-A14B',
    sizeBytes: 14294742832,
    notes: 'One of the two MoE expert models required for WAN 2.2 image-to-video.',
  }),
  [modelKey('loras', 'wan2.2_i2v_lightx2v_4steps_lora_v1_high_noise.safetensors')]: createModelRecipe({
    filename: 'wan2.2_i2v_lightx2v_4steps_lora_v1_high_noise.safetensors',
    targetSubdir: 'loras',
    displayName: 'WAN 2.2 4-step high-noise LoRA',
    downloadUrl: hfResolve('Comfy-Org/Wan_2.2_ComfyUI_Repackaged', 'split_files/loras/wan2.2_i2v_lightx2v_4steps_lora_v1_high_noise.safetensors'),
    sourceUrl: hfBlob('Comfy-Org/Wan_2.2_ComfyUI_Repackaged', 'split_files/loras/wan2.2_i2v_lightx2v_4steps_lora_v1_high_noise.safetensors'),
    licenseUrl: 'https://huggingface.co/lightx2v/Wan2.2-Lightning',
    sizeBytes: 1230000000,
    sha256: 'd176c808d6fc461999b68e321efcb7501b20b8c3797523ed0df14f7d1deff11e',
    notes: 'ComfyUI-repackaged filename that matches the bundled WAN workflow.',
  }),
  [modelKey('loras', 'wan2.2_i2v_lightx2v_4steps_lora_v1_low_noise.safetensors')]: createModelRecipe({
    filename: 'wan2.2_i2v_lightx2v_4steps_lora_v1_low_noise.safetensors',
    targetSubdir: 'loras',
    displayName: 'WAN 2.2 4-step low-noise LoRA',
    downloadUrl: hfResolve('Comfy-Org/Wan_2.2_ComfyUI_Repackaged', 'split_files/loras/wan2.2_i2v_lightx2v_4steps_lora_v1_low_noise.safetensors'),
    sourceUrl: hfBlob('Comfy-Org/Wan_2.2_ComfyUI_Repackaged', 'split_files/loras/wan2.2_i2v_lightx2v_4steps_lora_v1_low_noise.safetensors'),
    licenseUrl: 'https://huggingface.co/lightx2v/Wan2.2-Lightning',
    sizeBytes: 1230000000,
    sha256: '024f21de095bc8fad9809ded3e9e49a2e170dcf27075da8145ba7d60d8aab7f9',
    notes: 'ComfyUI-repackaged filename that matches the bundled WAN workflow.',
  }),
  [modelKey('diffusion_models', 'wan2.2_i2v_low_noise_14B_fp8_scaled.safetensors')]: createModelRecipe({
    filename: 'wan2.2_i2v_low_noise_14B_fp8_scaled.safetensors',
    targetSubdir: 'diffusion_models',
    displayName: 'WAN 2.2 low-noise expert diffusion model',
    downloadUrl: hfResolve('Comfy-Org/Wan_2.2_ComfyUI_Repackaged', 'split_files/diffusion_models/wan2.2_i2v_low_noise_14B_fp8_scaled.safetensors'),
    sourceUrl: hfBlob('Comfy-Org/Wan_2.2_ComfyUI_Repackaged', 'split_files/diffusion_models/wan2.2_i2v_low_noise_14B_fp8_scaled.safetensors'),
    licenseUrl: 'https://huggingface.co/Wan-AI/Wan2.2-I2V-A14B',
    sizeBytes: 14294742832,
    notes: 'One of the two MoE expert models required for WAN 2.2 image-to-video.',
  }),
  [modelKey('vae', 'wan_2.1_vae.safetensors')]: createModelRecipe({
    filename: 'wan_2.1_vae.safetensors',
    targetSubdir: 'vae',
    displayName: 'WAN 2.1 VAE',
    downloadUrl: hfResolve('Comfy-Org/Wan_2.2_ComfyUI_Repackaged', 'split_files/vae/wan_2.1_vae.safetensors'),
    sourceUrl: hfBlob('Comfy-Org/Wan_2.2_ComfyUI_Repackaged', 'split_files/vae/wan_2.1_vae.safetensors'),
    licenseUrl: 'https://huggingface.co/Wan-AI/Wan2.2-I2V-A14B',
    sizeBytes: 253815318,
    notes: 'Shared VAE for the bundled WAN 2.2 workflow.',
  }),
  [modelKey('diffusion_models', 'wan2.2_t2v_high_noise_14B_fp8_scaled.safetensors')]: createModelRecipe({
    filename: 'wan2.2_t2v_high_noise_14B_fp8_scaled.safetensors',
    targetSubdir: 'diffusion_models',
    displayName: 'WAN 2.2 T2V high-noise expert diffusion model',
    downloadUrl: hfResolve('Comfy-Org/Wan_2.2_ComfyUI_Repackaged', 'split_files/diffusion_models/wan2.2_t2v_high_noise_14B_fp8_scaled.safetensors'),
    sourceUrl: hfBlob('Comfy-Org/Wan_2.2_ComfyUI_Repackaged', 'split_files/diffusion_models/wan2.2_t2v_high_noise_14B_fp8_scaled.safetensors'),
    licenseUrl: 'https://huggingface.co/Wan-AI/Wan2.2-T2V-A14B',
    sizeBytes: 14293923632,
    notes: 'One of the two MoE expert models required for WAN 2.2 text-to-video.',
  }),
  [modelKey('diffusion_models', 'wan2.2_t2v_low_noise_14B_fp8_scaled.safetensors')]: createModelRecipe({
    filename: 'wan2.2_t2v_low_noise_14B_fp8_scaled.safetensors',
    targetSubdir: 'diffusion_models',
    displayName: 'WAN 2.2 T2V low-noise expert diffusion model',
    downloadUrl: hfResolve('Comfy-Org/Wan_2.2_ComfyUI_Repackaged', 'split_files/diffusion_models/wan2.2_t2v_low_noise_14B_fp8_scaled.safetensors'),
    sourceUrl: hfBlob('Comfy-Org/Wan_2.2_ComfyUI_Repackaged', 'split_files/diffusion_models/wan2.2_t2v_low_noise_14B_fp8_scaled.safetensors'),
    licenseUrl: 'https://huggingface.co/Wan-AI/Wan2.2-T2V-A14B',
    sizeBytes: 14293923632,
    notes: 'One of the two MoE expert models required for WAN 2.2 text-to-video.',
  }),
  [modelKey('loras', 'wan2.2_t2v_lightx2v_4steps_lora_v1.1_high_noise.safetensors')]: createModelRecipe({
    filename: 'wan2.2_t2v_lightx2v_4steps_lora_v1.1_high_noise.safetensors',
    targetSubdir: 'loras',
    displayName: 'WAN 2.2 T2V 4-step high-noise LoRA',
    downloadUrl: hfResolve('Comfy-Org/Wan_2.2_ComfyUI_Repackaged', 'split_files/loras/wan2.2_t2v_lightx2v_4steps_lora_v1.1_high_noise.safetensors'),
    sourceUrl: hfBlob('Comfy-Org/Wan_2.2_ComfyUI_Repackaged', 'split_files/loras/wan2.2_t2v_lightx2v_4steps_lora_v1.1_high_noise.safetensors'),
    licenseUrl: 'https://huggingface.co/lightx2v/Wan2.2-Lightning',
    sizeBytes: 1226977424,
    notes: 'Speed LoRA used by the bundled WAN 2.2 text-to-video workflow.',
  }),
  [modelKey('loras', 'wan2.2_t2v_lightx2v_4steps_lora_v1.1_low_noise.safetensors')]: createModelRecipe({
    filename: 'wan2.2_t2v_lightx2v_4steps_lora_v1.1_low_noise.safetensors',
    targetSubdir: 'loras',
    displayName: 'WAN 2.2 T2V 4-step low-noise LoRA',
    downloadUrl: hfResolve('Comfy-Org/Wan_2.2_ComfyUI_Repackaged', 'split_files/loras/wan2.2_t2v_lightx2v_4steps_lora_v1.1_low_noise.safetensors'),
    sourceUrl: hfBlob('Comfy-Org/Wan_2.2_ComfyUI_Repackaged', 'split_files/loras/wan2.2_t2v_lightx2v_4steps_lora_v1.1_low_noise.safetensors'),
    licenseUrl: 'https://huggingface.co/lightx2v/Wan2.2-Lightning',
    sizeBytes: 1226977424,
    notes: 'Speed LoRA used by the bundled WAN 2.2 text-to-video workflow.',
  }),
  [modelKey('diffusion_models', 'longcat_image_bf16.safetensors')]: createModelRecipe({
    filename: 'longcat_image_bf16.safetensors',
    targetSubdir: 'diffusion_models',
    displayName: 'LongCat Image BF16 diffusion model',
    downloadUrl: hfResolve('Comfy-Org/LongCat-Image', 'split_files/diffusion_models/longcat_image_bf16.safetensors'),
    sourceUrl: hfBlob('Comfy-Org/LongCat-Image', 'split_files/diffusion_models/longcat_image_bf16.safetensors'),
    licenseUrl: 'https://huggingface.co/Comfy-Org/LongCat-Image',
    sizeBytes: 12541383144,
    sha256: '7c83c314a3d879d43e5700072033256000f46a56900ae48b209a77ac1921488b',
    notes: 'Primary local text-to-image model used by the bundled LongCat workflow.',
  }),
  [modelKey('diffusion_models', 'ernie-image-turbo.safetensors')]: createModelRecipe({
    filename: 'ernie-image-turbo.safetensors',
    targetSubdir: 'diffusion_models',
    displayName: 'ERNIE Image Turbo diffusion model',
    downloadUrl: hfResolve('Comfy-Org/ERNIE-Image', 'diffusion_models/ernie-image-turbo.safetensors'),
    sourceUrl: hfBlob('Comfy-Org/ERNIE-Image', 'diffusion_models/ernie-image-turbo.safetensors'),
    licenseUrl: 'https://huggingface.co/Comfy-Org/ERNIE-Image',
    sizeBytes: 16067025480,
    notes: 'Primary local model used by the bundled Ernie Image Turbo workflow.',
  }),
  [modelKey('text_encoders', 'ministral-3-3b.safetensors')]: createModelRecipe({
    filename: 'ministral-3-3b.safetensors',
    targetSubdir: 'text_encoders',
    displayName: 'Ministral 3 3B ERNIE text encoder',
    downloadUrl: hfResolve('Comfy-Org/ERNIE-Image', 'text_encoders/ministral-3-3b.safetensors'),
    sourceUrl: hfBlob('Comfy-Org/ERNIE-Image', 'text_encoders/ministral-3-3b.safetensors'),
    licenseUrl: 'https://huggingface.co/Comfy-Org/ERNIE-Image',
    sizeBytes: 7717637511,
    notes: 'Text encoder used by the bundled Ernie Image Turbo workflow.',
  }),
  [modelKey('text_encoders', 'ernie-image-prompt-enhancer.safetensors')]: createModelRecipe({
    filename: 'ernie-image-prompt-enhancer.safetensors',
    targetSubdir: 'text_encoders',
    displayName: 'ERNIE prompt enhancer text encoder',
    downloadUrl: hfResolve('Comfy-Org/ERNIE-Image', 'text_encoders/ernie-image-prompt-enhancer.safetensors'),
    sourceUrl: hfBlob('Comfy-Org/ERNIE-Image', 'text_encoders/ernie-image-prompt-enhancer.safetensors'),
    licenseUrl: 'https://huggingface.co/Comfy-Org/ERNIE-Image',
    sizeBytes: 6877439999,
    notes: 'Prompt enhancement encoder used by the bundled Ernie Image Turbo workflow.',
  }),
  [modelKey('vae', 'flux2-vae.safetensors')]: createModelRecipe({
    filename: 'flux2-vae.safetensors',
    targetSubdir: 'vae',
    displayName: 'Flux 2 VAE',
    downloadUrl: hfResolve('Comfy-Org/ERNIE-Image', 'vae/flux2-vae.safetensors'),
    sourceUrl: hfBlob('Comfy-Org/ERNIE-Image', 'vae/flux2-vae.safetensors'),
    licenseUrl: 'https://huggingface.co/Comfy-Org/ERNIE-Image',
    sizeBytes: 336213556,
    notes: 'Flux 2 VAE used by the bundled Ernie Image Turbo workflow.',
  }),
  [modelKey('diffusion_models', 'flux2_dev_fp8mixed.safetensors')]: createModelRecipe({
    filename: 'flux2_dev_fp8mixed.safetensors',
    targetSubdir: 'diffusion_models',
    displayName: 'Flux 2 Dev FP8 mixed diffusion model',
    downloadUrl: hfResolve('Comfy-Org/flux2-dev', 'split_files/diffusion_models/flux2_dev_fp8mixed.safetensors'),
    sourceUrl: hfBlob('Comfy-Org/flux2-dev', 'split_files/diffusion_models/flux2_dev_fp8mixed.safetensors'),
    licenseUrl: 'https://huggingface.co/black-forest-labs/FLUX.2-dev',
    sizeBytes: 35455599592,
    notes: 'Primary local model used by the bundled Flux 2 text-to-image workflow.',
  }),
  [modelKey('text_encoders', 'mistral_3_small_flux2_bf16.safetensors')]: createModelRecipe({
    filename: 'mistral_3_small_flux2_bf16.safetensors',
    targetSubdir: 'text_encoders',
    displayName: 'Mistral 3 Small Flux 2 BF16 text encoder',
    downloadUrl: hfResolve('Comfy-Org/flux2-dev', 'split_files/text_encoders/mistral_3_small_flux2_bf16.safetensors'),
    sourceUrl: hfBlob('Comfy-Org/flux2-dev', 'split_files/text_encoders/mistral_3_small_flux2_bf16.safetensors'),
    licenseUrl: 'https://huggingface.co/black-forest-labs/FLUX.2-dev',
    sizeBytes: 35584897447,
    notes: 'Text encoder used by the bundled Flux 2 text-to-image workflow.',
  }),
  [modelKey('vae', 'full_encoder_small_decoder.safetensors')]: createModelRecipe({
    filename: 'full_encoder_small_decoder.safetensors',
    targetSubdir: 'vae',
    displayName: 'Flux 2 full encoder small decoder VAE',
    downloadUrl: hfResolve('black-forest-labs/FLUX.2-small-decoder', 'full_encoder_small_decoder.safetensors'),
    sourceUrl: hfBlob('black-forest-labs/FLUX.2-small-decoder', 'full_encoder_small_decoder.safetensors'),
    licenseUrl: 'https://huggingface.co/black-forest-labs/FLUX.2-small-decoder',
    sizeBytes: 249519092,
    sha256: 'ea4273f02d1fafbf8e1d1c2cf6018ed8748652eb0bf34f2dd91171f16f15ab62',
    notes: 'VAE used by the bundled Flux 2 text-to-image workflow.',
  }),
  [modelKey('loras', 'Flux_2-Turbo-LoRA_comfyui.safetensors')]: createModelRecipe({
    filename: 'Flux_2-Turbo-LoRA_comfyui.safetensors',
    targetSubdir: 'loras',
    displayName: 'Flux 2 Turbo LoRA',
    downloadUrl: hfResolve('Comfy-Org/flux2-dev', 'split_files/loras/Flux_2-Turbo-LoRA_comfyui.safetensors'),
    sourceUrl: hfBlob('Comfy-Org/flux2-dev', 'split_files/loras/Flux_2-Turbo-LoRA_comfyui.safetensors'),
    licenseUrl: 'https://huggingface.co/fal/FLUX.2-dev-Turbo',
    sizeBytes: 2760814880,
    sha256: '011487390b8020baf22a9d543930c90d74a4809b7241bee6b0622777b17b413b',
    notes: 'Speed LoRA used by the bundled Flux 2 text-to-image workflow.',
  }),
  [modelKey('frame_interpolation', 'film_net_fp16.safetensors')]: createModelRecipe({
    filename: 'film_net_fp16.safetensors',
    targetSubdir: 'frame_interpolation',
    displayName: 'FILM frame interpolation model',
    downloadUrl: hfResolve('Comfy-Org/frame_interpolation', 'frame_interpolation/film_net_fp16.safetensors'),
    sourceUrl: hfBlob('Comfy-Org/frame_interpolation', 'frame_interpolation/film_net_fp16.safetensors'),
    licenseUrl: 'https://huggingface.co/Comfy-Org/frame_interpolation',
    sizeBytes: 68882302,
    notes: 'FILM model used by the bundled frame interpolation workflow.',
  }),
  [modelKey('diffusion_models', 'z_image_turbo_bf16.safetensors')]: createModelRecipe({
    filename: 'z_image_turbo_bf16.safetensors',
    targetSubdir: 'diffusion_models',
    displayName: 'Z Image Turbo BF16 diffusion model',
    downloadUrl: hfResolve('Comfy-Org/z_image_turbo', 'split_files/diffusion_models/z_image_turbo_bf16.safetensors'),
    sourceUrl: hfBlob('Comfy-Org/z_image_turbo', 'split_files/diffusion_models/z_image_turbo_bf16.safetensors'),
    licenseUrl: 'https://huggingface.co/Tongyi-MAI/Z-Image-Turbo',
    sizeBytes: 12309866400,
    notes: 'Primary local text-to-image model used by the bundled Z Image Turbo workflow.',
  }),
  [modelKey('diffusion_models', 'z_image_turbo-Q4_K_M.gguf')]: createModelRecipe({
    filename: 'z_image_turbo-Q4_K_M.gguf',
    targetSubdir: 'diffusion_models',
    displayName: 'Z Image Turbo GGUF Q4_K_M diffusion model',
    downloadUrl: hfResolve('jayn7/Z-Image-Turbo-GGUF', 'z_image_turbo-Q4_K_M.gguf'),
    sourceUrl: hfBlob('jayn7/Z-Image-Turbo-GGUF', 'z_image_turbo-Q4_K_M.gguf'),
    licenseUrl: 'https://huggingface.co/Tongyi-MAI/Z-Image-Turbo',
    sizeBytes: 4981532736,
    sha256: '745ec270db042409fde084d6b5cfccabf214a7fe5a494edf994a391125656afd',
    notes: 'Q4_K_M model used by the bundled local Z Image Turbo GGUF workflow.',
  }),
})

export function getNodeInstallInfo(classType = '') {
  const normalized = String(classType || '').trim()
  if (!normalized) {
    return Object.freeze({
      classType: '',
      kind: 'unknown',
      displayName: 'Unknown dependency',
      docsUrl: COMFY_REGISTRY_URL,
      notes: 'No class type was provided for this node dependency.',
    })
  }

  const autoPack = AUTO_NODE_PACK_BY_CLASS_TYPE[normalized]
  if (autoPack) {
    return Object.freeze({
      classType: normalized,
      ...autoPack,
    })
  }

  if (CORE_NODE_HINTS[normalized]) {
    return CORE_NODE_HINTS[normalized]
  }

  if (MANUAL_NODE_HINTS[normalized]) {
    return MANUAL_NODE_HINTS[normalized]
  }

  return Object.freeze({
    classType: normalized,
    kind: 'manual',
    displayName: 'Manual setup required',
    docsUrl: COMFY_REGISTRY_URL,
    searchTerm: normalized,
    notes: 'No curated install recipe is available yet for this node class.',
  })
}

export function getNodePackInstallInfo(packId = '') {
  const normalized = String(packId || '').trim()
  return CURATED_NODE_PACKS.find(pack => pack.id === normalized) || null
}

export function getModelInstallInfo({ filename = '', targetSubdir = '' } = {}) {
  const key = modelKey(targetSubdir, filename)
  const recipe = MODEL_INSTALL_RECIPES[key]
  if (recipe) return recipe

  const importedRecipe = getImportedModelRecipe({ filename, targetSubdir })
  if (importedRecipe) return importedRecipe

  return Object.freeze({
    filename: String(filename || '').trim(),
    targetSubdir: String(targetSubdir || '').trim(),
    displayName: String(filename || '').trim() || 'Unknown model',
    downloadUrl: '',
    sourceUrl: '',
    licenseUrl: '',
    sizeBytes: null,
    sha256: '',
    notes: 'No curated download recipe is available yet for this model.',
  })
}

export function isNodeAutoInstallable(classType = '') {
  return getNodeInstallInfo(classType).kind === 'auto'
}

export function isModelAutoInstallable(model = {}) {
  return Boolean(getModelInstallInfo(model).downloadUrl)
}
